//! Declarative categorization rules. Each rule ties a curated needle list to a category, a signal
//! field (where/how it matches — see `signals::Field`), and a weight (how strong — see `score`).
//! This is intentionally data, not logic: adding a product means adding needles, never reordering a
//! cascade. Keep needles lowercase; Token fields (`Name`, `Product`) match whole words, so multi-word
//! and hyphenated needles are fine (`visual studio`, `7-zip`) and never fire on a substring.

use super::super::AppCategory;
use super::super::AppCategory::{
    Ai, Browsers, Communication, Development, Editors, FileCloud, Games, Media, Productivity,
    Security, System, Utilities, WindowsFeatures,
};
use super::score::{
    DECISIVE, DESC, EXE, EXE_GLUE, FEATURE, INSTALL_TREE, NAME, PATH, PRODUCT, PUBLISHER,
};
use super::signals::Field;
use super::signals::Field::{Desc, ExeContains, ExeEq, Feature, Name, Path, Product, Publisher};

pub(super) struct Rule {
    pub category: AppCategory,
    pub field: Field,
    pub weight: i32,
    pub needles: &'static [&'static str],
}

const fn rule(
    category: AppCategory,
    field: Field,
    weight: i32,
    needles: &'static [&'static str],
) -> Rule {
    Rule {
        category,
        field,
        weight,
        needles,
    }
}

pub(super) static RULES: &[Rule] = &[
    // ---- Games ----------------------------------------------------------------------------------
    rule(
        Games,
        Publisher,
        PUBLISHER,
        &[
            "blizzard",
            "valve",
            "riot games",
            "electronic arts",
            "ea games",
            "ea sports",
            "ubisoft",
            "epic games",
            "rockstar games",
            "bethesda",
            "cd projekt",
            "mihoyo",
            "hoyoverse",
            "cognosphere",
            "wargaming",
            "activision",
            "2k games",
            "square enix",
            "bandai namco",
            "capcom",
            "gaijin",
            "larian",
            "warhorse",
        ],
    ),
    rule(
        Games,
        Path,
        INSTALL_TREE,
        &[
            r"\steamapps\",
            r"\battle.net\",
            r"\epic games\",
            r"\riot games\",
            r"\gog galaxy\",
            r"\ea games\",
            r"\origin games\",
            r"\ubisoft\",
            r"\rockstar games\",
            r"\wargaming.net\",
            r"\hoyoplay\",
            r"\mihoyo\",
        ],
    ),
    rule(Games, ExeEq, EXE, &["wow", "battle.net"]),
    // A game built on a known engine (the engine name lands in the PE file description or product
    // name) — a list-free way to catch the indie long tail whose title is in no keyword list. Unity
    // is omitted deliberately: its marker is too generic to match by substring without false hits.
    rule(
        Games,
        Desc,
        DESC,
        &[
            "godot engine",
            "unreal engine",
            "gamemaker",
            "game maker",
            "rpg maker",
            "ren'py",
            "renpy",
        ],
    ),
    rule(
        Games,
        Product,
        PRODUCT,
        &["godot engine", "unreal engine", "gamemaker", "rpg maker"],
    ),
    // A user's dedicated games folder is a strong hint on its own, even for an unknown title.
    rule(Games, Path, PATH, &[r"\games\"]),
    rule(
        Games,
        Name,
        NAME,
        &[
            "steam",
            "battle.net",
            "epic games",
            "gog",
            "game",
            "minecraft",
            "roblox",
            "backpack battles",
            "warcraft",
            "hearthstone",
            "dota",
            "valorant",
            "league of legends",
            "apex legends",
            "fortnite",
            "grand theft auto",
            "gta",
            "witcher",
            "cyberpunk",
            "overwatch",
            "diablo",
            "starcraft",
            "genshin",
            "honkai",
            "counter-strike",
            "cs2",
            "csgo",
            "pubg",
            "terraria",
            "stardew",
            "elden ring",
            "dark souls",
            "baldur",
            "warframe",
            "path of exile",
            "dead by daylight",
            "rainbow six",
            "call of duty",
            "warzone",
            "battlefield",
            "world of tanks",
            "war thunder",
            "palworld",
            "valheim",
            "clash of clans",
            "clash royale",
        ],
    ),
    // ---- AI & Agents ----------------------------------------------------------------------------
    rule(Ai, Publisher, PUBLISHER, &["openai", "anthropic"]),
    rule(
        Ai,
        Name,
        NAME,
        &[
            "claude",
            "chatgpt",
            "openai",
            "codex",
            "ollama",
            "lm studio",
            "gemini",
            "copilot",
            "cursor",
            "ai agent",
            "perplexity",
            "mistral",
            "anythingllm",
            "msty",
            "opencode",
            "aider",
            "cline",
            "roo code",
        ],
    ),
    rule(
        Ai,
        ExeEq,
        EXE,
        &[
            "claude", "chatgpt", "codex", "ollama", "cursor", "opencode", "msty", "aider",
        ],
    ),
    // ---- Development ----------------------------------------------------------------------------
    rule(
        Development,
        Publisher,
        PUBLISHER,
        &[
            "jetbrains",
            "github, inc",
            "docker, inc",
            "gitkraken",
            "mongodb",
        ],
    ),
    rule(
        Development,
        Name,
        NAME,
        &[
            "visual studio",
            "vscode",
            "code",
            "rustrover",
            "pycharm",
            "webstorm",
            "intellij",
            "android studio",
            "git",
            "github",
            "docker",
            "postman",
            "terminal",
            "sublime text",
            "notepad++",
            "node.js",
            "nodejs",
            "python",
            "github desktop",
            "sourcetree",
            "gitkraken",
            "dbeaver",
            "tableplus",
            "heidisql",
            "insomnia",
            "clion",
            "datagrip",
            "phpstorm",
            "cmake",
            "mongodb",
            "studio 3t",
            "robo 3t",
            "dbgate",
            "beekeeper",
        ],
    ),
    rule(
        Development,
        ExeEq,
        EXE,
        &[
            "devenv",
            "code",
            "rustrover",
            "pycharm64",
            "webstorm64",
            "idea64",
            "postman",
        ],
    ),
    // ---- Editors & Design -----------------------------------------------------------------------
    rule(
        Editors,
        Publisher,
        PUBLISHER,
        &["adobe", "maxon", "blackmagic", "affinity", "corel"],
    ),
    rule(
        Editors,
        Name,
        NAME,
        &[
            "photoshop",
            "illustrator",
            "lightroom",
            "figma",
            "gimp",
            "inkscape",
            "blender",
            "paint.net",
            "canva",
            "davinci resolve",
            "premiere",
            "after effects",
            "affinity",
            "krita",
            "clip studio",
            "capcut",
            "darktable",
        ],
    ),
    rule(
        Editors,
        ExeEq,
        EXE,
        &[
            "photoshop",
            "illustrator",
            "gimp",
            "blender",
            "krita",
            "inkscape",
        ],
    ),
    // ---- Office & Productivity ------------------------------------------------------------------
    // PDF readers are Productivity even when the vendor (Adobe) would otherwise map to Editors; this
    // decisive weight must beat the publisher rule.
    rule(
        Productivity,
        ExeContains,
        DECISIVE,
        &["acrord32", "acrobat"],
    ),
    rule(
        Productivity,
        Path,
        INSTALL_TREE,
        &[
            r"\microsoft office\",
            r"\microsoft\office\",
            r"\libreoffice\",
            r"\onlyoffice\",
            r"\wps office\",
        ],
    ),
    rule(
        Productivity,
        Product,
        PRODUCT,
        &[
            "notion",
            "obsidian",
            "evernote",
            "libreoffice",
            "microsoft office",
        ],
    ),
    rule(
        Productivity,
        Name,
        NAME,
        &[
            "microsoft office",
            "winword",
            "excel",
            "powerpnt",
            "onenote",
            "outlook",
            "libreoffice",
            "openoffice",
            "onlyoffice",
            "wps office",
            "notion",
            "obsidian",
            "evernote",
            "joplin",
            "logseq",
            "acrobat",
            "acrord32",
            "adobe reader",
            "foxit",
            "sumatra",
            "pdf-xchange",
            "calibre",
            "zotero",
            "anki",
        ],
    ),
    rule(
        Productivity,
        ExeEq,
        EXE,
        &[
            "winword", "excel", "powerpnt", "onenote", "outlook", "scalc", "swriter", "simpress",
        ],
    ),
    // ---- Browsers -------------------------------------------------------------------------------
    rule(Browsers, Publisher, PUBLISHER, &["mozilla"]),
    rule(
        Browsers,
        Path,
        INSTALL_TREE,
        &[
            r"\mozilla firefox\",
            r"\google\chrome\",
            r"\microsoft\edge\",
        ],
    ),
    rule(
        Browsers,
        Name,
        NAME,
        &[
            "chrome", "firefox", "edge", "opera", "brave", "vivaldi", "browser", "yandex",
            "chromium", "thorium",
        ],
    ),
    rule(
        Browsers,
        ExeEq,
        EXE,
        &[
            "chrome", "firefox", "msedge", "opera", "brave", "vivaldi", "chromium",
        ],
    ),
    rule(Browsers, Desc, DESC, &["internet browser", "web browser"]),
    // ---- Media ----------------------------------------------------------------------------------
    rule(Media, Publisher, PUBLISHER, &["videolan", "spotify"]),
    rule(
        Media,
        Name,
        NAME,
        &[
            "vlc",
            "spotify",
            "foobar",
            "audacity",
            "obs",
            "media player",
            "potplayer",
            "mpc-hc",
            "mpc-be",
            "kmplayer",
            "aimp",
            "winamp",
            "itunes",
            "plex",
            "kodi",
            "deezer",
            "tidal",
            "jellyfin",
        ],
    ),
    rule(
        Media,
        ExeEq,
        EXE,
        &[
            "vlc",
            "spotify",
            "foobar2000",
            "audacity",
            "potplayer",
            "aimp",
            "winamp",
            "itunes",
        ],
    ),
    rule(Media, Desc, DESC, &["media player"]),
    // ---- Communication --------------------------------------------------------------------------
    rule(
        Communication,
        Publisher,
        PUBLISHER,
        &["telegram", "whatsapp", "discord inc"],
    ),
    rule(
        Communication,
        Name,
        NAME,
        &[
            "discord",
            "telegram",
            "whatsapp",
            "slack",
            "teams",
            "zoom",
            "skype",
            "signal",
            "viber",
            "wechat",
            "element",
            "thunderbird",
        ],
    ),
    rule(
        Communication,
        ExeEq,
        EXE,
        &[
            "discord",
            "telegram",
            "whatsapp",
            "slack",
            "zoom",
            "skype",
            "thunderbird",
        ],
    ),
    rule(Communication, Desc, DESC, &["email client", "e-mail"]),
    // ---- File & Cloud ---------------------------------------------------------------------------
    rule(
        FileCloud,
        Name,
        NAME,
        &[
            "7-zip",
            "winrar",
            "peazip",
            "bandizip",
            "nanazip",
            "onedrive",
            "dropbox",
            "google drive",
            "yandex disk",
            "mega",
            "nextcloud",
            "syncthing",
            "total commander",
            "everything",
            "filezilla",
            "winscp",
        ],
    ),
    rule(
        FileCloud,
        ExeEq,
        EXE,
        &[
            "winrar",
            "7zfm",
            "peazip",
            "bandizip",
            "nanazip",
            "dropbox",
            "onedrive",
            "filezilla",
            "winscp",
            "totalcmd64",
        ],
    ),
    // ---- Security & Privacy ---------------------------------------------------------------------
    rule(
        Security,
        Publisher,
        PUBLISHER,
        &[
            "kaspersky",
            "bitdefender",
            "malwarebytes",
            "eset",
            "avast",
            "avg technologies",
            "doctor web",
            "avira",
            "sophos",
            "trend micro",
            "f-secure",
            "emsisoft",
            "sentinelone",
            "crowdstrike",
        ],
    ),
    rule(
        Security,
        Name,
        NAME,
        &[
            // Anti-virus / endpoint security.
            "antivirus",
            "anti-virus",
            "antimalware",
            "anti-malware",
            "endpoint security",
            "internet security",
            "kaspersky",
            "bitdefender",
            "malwarebytes",
            "eset",
            "avast",
            "norton",
            "mcafee",
            "drweb",
            "dr.web",
            // Password managers.
            "keepass",
            "bitwarden",
            "1password",
            "dashlane",
            "nordpass",
            "proton pass",
            // VPN / proxy clients.
            "vpn",
            "proxy",
            "wireguard",
            "openvpn",
            "hiddify",
            "nekoray",
            "nekobox",
            "clash verge",
            "clashx",
            "mihomo",
            "v2ray",
            "xray",
            "sing-box",
            "shadowsocks",
            "outline",
            "cloudflare warp",
            "mullvad",
            "proton vpn",
            "nordvpn",
            "expressvpn",
            "surfshark",
            "windscribe",
            "ipvanish",
            "tunnelbear",
            "psiphon",
        ],
    ),
    rule(
        Security,
        Product,
        PRODUCT,
        &[
            "antivirus",
            "anti-virus",
            "antimalware",
            "anti-malware",
            "endpoint security",
            "internet security",
            "vpn",
            "vpn client",
            "proxy",
            "proxy client",
            "password manager",
        ],
    ),
    // Executables that glue a marker onto the product name (`SotaVPN.exe`, `FooProxy.exe`).
    rule(Security, ExeContains, EXE_GLUE, &["vpn", "proxy"]),
    rule(
        Security,
        Desc,
        DESC,
        &[
            "antivirus",
            "anti-virus",
            "antimalware",
            "anti-malware",
            "endpoint security",
            "internet security",
            "vpn client",
            "proxy client",
            "password manager",
        ],
    ),
    // ---- System ---------------------------------------------------------------------------------
    // Mostly shadowed by the Windows-feature markers below (which are higher weight); kept for the
    // rare console tool that is not an inbox feature.
    rule(
        System,
        Name,
        NAME,
        &["command prompt", "powershell", "командная строка"],
    ),
    // ---- Utilities ------------------------------------------------------------------------------
    rule(
        Utilities,
        Name,
        NAME,
        &[
            "powertoys",
            "rufus",
            "verifier",
            "configure",
            "utility",
            "uninstaller",
            "cpu-z",
            "gpu-z",
            "hwinfo",
            "hwmonitor",
            "crystaldisk",
            "aida64",
            "msi afterburner",
            "rivatuner",
            "treesize",
            "windirstat",
            "ccleaner",
            "revo uninstaller",
            "display driver uninstaller",
            "victoria",
            "memtest",
            "furmark",
            "winmtr",
        ],
    ),
    // =============================================================================================
    // Extended common-app coverage. These broaden the population beyond what is installed on any one
    // machine: publisher rules generalize across every product a vendor ships, and the name lists are
    // the widely-used apps a typical Windows user is likely to have. Curated to distinctive tokens to
    // keep whole-word matching false-positive free. Add here rather than reordering the base lists.
    // =============================================================================================
    // ---- Games (stores, launchers, mod tools) ---------------------------------------------------
    rule(
        Games,
        Name,
        NAME,
        &[
            "xbox",
            "curseforge",
            "playnite",
            "ea app",
            "gog galaxy",
            "riot client",
            "faceit",
            "geforce now",
            "amazon games",
            "ubisoft connect",
            "rockstar games launcher",
            "modrinth",
            "prism launcher",
            "atlauncher",
            "multimc",
            "vortex",
            "playstation",
            "epic games launcher",
        ],
    ),
    // ---- AI & Agents ----------------------------------------------------------------------------
    rule(Ai, Publisher, PUBLISHER, &["mistral ai", "perplexity"]),
    rule(
        Ai,
        Name,
        NAME,
        &[
            "codeium",
            "windsurf",
            "gpt4all",
            "deepseek",
            "tabnine",
            "librechat",
            "comfyui",
            "fooocus",
            "invokeai",
            "pinokio",
            "automatic1111",
            "stable diffusion",
            "kobold",
            "jan.ai",
        ],
    ),
    // ---- Development (editors, runtimes, databases, terminals, VCS) -----------------------------
    rule(
        Development,
        Publisher,
        PUBLISHER,
        &[
            "postgresql",
            "python software foundation",
            "hashicorp",
            "atlassian",
            "the qt company",
            "espressif",
        ],
    ),
    rule(
        Development,
        Name,
        NAME,
        &[
            "vscodium",
            "zed",
            "neovim",
            "goland",
            "rider",
            "deno",
            "bun",
            "pnpm",
            "rustup",
            "cargo",
            "anaconda",
            "miniconda",
            "jupyter",
            "spyder",
            "rstudio",
            "matlab",
            "arduino",
            "platformio",
            "kicad",
            "docker desktop",
            "podman",
            "terraform",
            "vagrant",
            "ngrok",
            "bruno",
            "mysql",
            "mariadb",
            "postgresql",
            "postgres",
            "pgadmin",
            "navicat",
            "sqlitestudio",
            "azure data studio",
            "mongodb compass",
            "redisinsight",
            "wezterm",
            "alacritty",
            "tabby",
            "mobaxterm",
            "putty",
            "termius",
            "tortoisegit",
            "tortoisesvn",
            "smartgit",
            "sublime merge",
            "winmerge",
            "beyond compare",
            "eclipse",
            "netbeans",
            "qt creator",
            "ghidra",
            "x64dbg",
            "wireshark",
            "java",
            "jdk",
            "openjdk",
            "temurin",
            "dotnet",
            "xampp",
            "laragon",
        ],
    ),
    // ---- Editors & Design (image, video, CAD) ---------------------------------------------------
    rule(
        Editors,
        Publisher,
        PUBLISHER,
        &[
            "autodesk",
            "wondershare",
            "techsmith",
            "topaz labs",
            "skylum",
        ],
    ),
    rule(
        Editors,
        Name,
        NAME,
        &[
            "clipchamp",
            "shotcut",
            "kdenlive",
            "handbrake",
            "filmora",
            "camtasia",
            "vegas pro",
            "photopea",
            "aseprite",
            "autocad",
            "fusion 360",
            "sketchup",
            "coreldraw",
            "acdsee",
            "irfanview",
            "xnview",
            "faststone",
            "imageglass",
            "zbrush",
            "cinema 4d",
            "solidworks",
            "freecad",
        ],
    ),
    // ---- Office & Productivity ------------------------------------------------------------------
    rule(
        Productivity,
        Publisher,
        PUBLISHER,
        &["the document foundation", "kingsoft"],
    ),
    rule(
        Productivity,
        Name,
        NAME,
        &[
            "powerpoint",
            "visio",
            "todoist",
            "ticktick",
            "microsoft to do",
            "grammarly",
            "deepl",
            "xmind",
            "typora",
            "okular",
            "sumatrapdf",
            "pdf24",
            "pdfsam",
            "trello",
            "clickup",
            "confluence",
            "anytype",
            "goodnotes",
            "apple books",
            "google keep",
        ],
    ),
    // ---- Browsers -------------------------------------------------------------------------------
    rule(
        Browsers,
        Publisher,
        PUBLISHER,
        &["brave software", "the tor project"],
    ),
    rule(
        Browsers,
        Name,
        NAME,
        &[
            "tor browser",
            "waterfox",
            "librewolf",
            "pale moon",
            "maxthon",
            "floorp",
            "zen browser",
            "opera gx",
            "mullvad browser",
            "comodo dragon",
        ],
    ),
    // ---- Media ----------------------------------------------------------------------------------
    rule(
        Media,
        Publisher,
        PUBLISHER,
        &["image-line", "ableton", "native instruments", "steinberg"],
    ),
    rule(
        Media,
        Name,
        NAME,
        &[
            "mpv",
            "musicbee",
            "clementine",
            "strawberry",
            "stremio",
            "emby",
            "youtube music",
            "soundcloud",
            "groove music",
            "apple music",
            "mediamonkey",
            "reaper",
            "fl studio",
            "ableton",
            "cubase",
            "studio one",
            "cakewalk",
            "lmms",
            "mixxx",
            "virtual dj",
            "rekordbox",
            "obs studio",
            "streamlabs",
            "xsplit",
            "nvidia broadcast",
        ],
    ),
    // ---- Communication --------------------------------------------------------------------------
    rule(
        Communication,
        Name,
        NAME,
        &[
            "microsoft teams",
            "webex",
            "jitsi",
            "mattermost",
            "threema",
            "kakaotalk",
            "messenger",
            "ferdium",
            "mailbird",
            "em client",
            "proton mail",
            "tutanota",
            "mailspring",
            "teamspeak",
            "mumble",
        ],
    ),
    // ---- File & Cloud (torrents, archivers, sync, transfer, file managers, imaging) -------------
    rule(
        FileCloud,
        Name,
        NAME,
        &[
            "utorrent",
            "bittorrent",
            "qbittorrent",
            "transmission",
            "deluge",
            "picotorrent",
            "winzip",
            "teracopy",
            "fastcopy",
            "freefilesync",
            "icloud",
            "pcloud",
            "rclone",
            "cyberduck",
            "xyplorer",
            "directory opus",
            "freecommander",
            "double commander",
            "duplicati",
            "macrium reflect",
            "aomei backupper",
            "ventoy",
            "balenaetcher",
            "poweriso",
            "ultraiso",
            "daemon tools",
            "wiztree",
            "spacesniffer",
        ],
    ),
    // ---- Security & Privacy ---------------------------------------------------------------------
    rule(
        Security,
        Publisher,
        PUBLISHER,
        &["avira", "sophos", "f-secure"],
    ),
    rule(
        Security,
        Name,
        NAME,
        &[
            "avira",
            "sophos",
            "f-secure",
            "adguard",
            "adwcleaner",
            "hitmanpro",
            "glasswire",
            "tailscale",
            "zerotier",
            "softether",
            "veracrypt",
            "cryptomator",
            "axcrypt",
            "keepassxc",
            "enpass",
            "authy",
            "2fas",
            "gpg4win",
            "kleopatra",
        ],
    ),
    // ---- Utilities (vendor control, hardware/diagnostics, remote, capture, launchers, tweaks) ---
    rule(
        Utilities,
        Publisher,
        PUBLISHER,
        &[
            "nvidia",
            "advanced micro devices",
            "realtek",
            "logitech",
            "razer",
            "corsair",
            "steelseries",
            "micro-star",
            "asustek",
            "gigabyte",
            "sysinternals",
            "nirsoft",
            "piriform",
            "geeks3d",
            "crystal dew world",
            "sordum",
        ],
    ),
    rule(
        Utilities,
        Name,
        NAME,
        &[
            "nvidia app",
            "geforce experience",
            "amd software",
            "radeon software",
            "msi center",
            "armoury crate",
            "aura sync",
            "icue",
            "razer synapse",
            "steelseries gg",
            "openrgb",
            "signalrgb",
            "logi options",
            "g hub",
            "fan control",
            "core temp",
            "throttlestop",
            "ryzen master",
            "cinebench",
            "3dmark",
            "occt",
            "prime95",
            "autoruns",
            "process explorer",
            "process hacker",
            "system informer",
            "autohotkey",
            "autoit",
            "sharex",
            "greenshot",
            "lightshot",
            "flameshot",
            "snagit",
            "teamviewer",
            "anydesk",
            "rustdesk",
            "tightvnc",
            "realvnc",
            "parsec",
            "moonlight",
            "listary",
            "flow launcher",
            "rainmeter",
            "wallpaper engine",
            "displayfusion",
            "translucenttb",
            "ditto",
            "bulk crap uninstaller",
            "iobit uninstaller",
            "chocolatey",
            "scoop",
            "ninite",
            "windows update blocker",
            "windhawk",
            "startallback",
            "explorerpatcher",
            "open shell",
            "classic shell",
        ],
    ),
    // ---- Windows Features -----------------------------------------------------------------------
    // Verbatim inbox markers (localized names, AUMIDs, MMC snap-ins, system exes). Matched as a
    // substring of the name+path blob so an AUMID or a localized shortcut name still lands.
    rule(WindowsFeatures, Feature, FEATURE, WINDOWS_FEATURE_MARKERS),
];

/// Inbox Windows shell apps, accessibility tools, management consoles, and administrative utilities.
static WINDOWS_FEATURE_MARKERS: &[&str] = &[
    "file explorer",
    "explorer.exe",
    "проводник",
    "snipping tool",
    "snippingtool.exe",
    "microsoft.screensketch",
    "ножницы",
    "get help",
    "microsoft.gethelp",
    "техническая поддержка",
    "remote desktop connection",
    "mstsc.exe",
    "подключение к удаленному рабочему столу",
    "calculator",
    "microsoft.windowscalculator",
    "калькулятор",
    "notepad",
    "microsoft.windowsnotepad",
    "блокнот",
    "microsoft paint",
    "mspaint.exe",
    "microsoft.paint",
    "камера",
    "microsoft.windowscamera",
    "clock",
    "microsoft.windowsalarms",
    "часы",
    "voice recorder",
    "sound recorder",
    "microsoft.windowssoundrecorder",
    "запись голоса",
    "звукозапись",
    "magnifier",
    "magnify.exe",
    "экранная лупа",
    "on-screen keyboard",
    "osk.exe",
    "экранная клавиатура",
    "narrator",
    "narrator.exe",
    "экранный диктор",
    "quick assist",
    "microsoftcorporationii.quickassist",
    "быстрая помощь",
    "windows security",
    "microsoft.sechealthui",
    "безопасность windows",
    "windows settings",
    "systemsettings.exe",
    "параметры",
    "microsoft.windows.administrativetools",
    "инструменты windows",
    "windows backup",
    "windowsbackup",
    "архивация windows",
    "microsoft.windowsstore",
    "microsoft store",
    "microsoft.windows.photos",
    "фотографии",
    "microsoft.bingweather",
    "погода",
    "microsoft.bingnews",
    "новости",
    "microsoft.microsoftstickynotes",
    "sticky notes",
    "записки",
    "microsoft.yourphone",
    "phone link",
    "связь с телефоном",
    "microsoft.windowsfeedbackhub",
    "feedback hub",
    "центр отзывов",
    "microsoft.windows.shell.rundialog",
    "выполнить",
    "windows media player legacy",
    "steps recorder",
    "psr.exe",
    "средство записи действий",
    "memory diagnostics tool",
    "mdsched.exe",
    "средство проверки памяти windows",
    "recoverydrive",
    "recoverydrive.exe",
    "диск восстановления",
    "iscsi initiator",
    "iscsicpl.exe",
    "инициатор iscsi",
    "computer management",
    "compmgmt.msc",
    "управление компьютером",
    "print management",
    "printmanagement.msc",
    "управление печатью",
    "device manager",
    "devmgmt.msc",
    "диспетчер устройств",
    "disk management",
    "diskmgmt.msc",
    "управление дисками",
    "event viewer",
    "eventvwr.msc",
    "просмотр событий",
    "task scheduler",
    "taskschd.msc",
    "планировщик задач",
    "планировщик заданий",
    "local security policy",
    "secpol.msc",
    "локальная политика безопасности",
    "group policy",
    "gpedit.msc",
    "групповая политика",
    "system configuration",
    "msconfig.exe",
    "конфигурация системы",
    "resource monitor",
    "resmon.exe",
    "монитор ресурсов",
    "performance monitor",
    "perfmon.msc",
    "системный монитор",
    "component services",
    "comexp.msc",
    "службы компонентов",
    "odbc data sources",
    "odbcad32.exe",
    "источники данных odbc",
    "system information",
    "msinfo32.exe",
    "сведения о системе",
    "control panel",
    "control.exe",
    "панель управления",
    "administrative tools",
    "windows tools",
    "администрирование",
    "средства windows",
    "registry editor",
    "regedit.exe",
    "редактор реестра",
    "disk cleanup",
    "cleanmgr.exe",
    "очистка диска",
    "defragment",
    "dfrgui.exe",
    "дефрагментация",
    "windows defender firewall",
    "wf.msc",
    "брандмауэр",
    "system restore",
    "rstrui.exe",
    "восстановление системы",
    "services.msc",
    "службы",
    "character map",
    "charmap.exe",
    "таблица символов",
    "command prompt",
    "cmd.exe",
    "командная строка",
    "windows powershell",
    "powershell.exe",
    "windows terminal",
    "microsoft.windowsterminal",
    "task manager",
    "taskmgr.exe",
    "диспетчер задач",
];
