use super::super::AppCategory;
use super::super::AppCategory::{
    Ai, Browsers, Communication, Development, Editors, FileCloud, Games, Media, Productivity,
    Security, System, Utilities, WindowsFeatures,
};
use super::score::{
    DECISIVE, DESC, EXE, EXE_GLUE, FEATURE, INSTALL_TREE, NAME, PATH, PRODUCT, PUBLISHER,
    VOCABULARY,
};
use super::signals::Field;
use super::signals::Field::{
    Association, Desc, ExeContains, ExeEq, Name, NameEq, Path, Product, Publisher,
};
use super::vocabulary;

pub(super) struct Rule {
    pub category: AppCategory,
    pub field: Field,
    pub weight: i32,
    pub needles: &'static [&'static str],
}

const fn rule(
    category: AppCategory,
    field: Field,
    weight: i32,
    needles: &'static [&'static str],
) -> Rule {
    Rule {
        category,
        field,
        weight,
        needles,
    }
}

pub(super) static RULES: &[Rule] = &[
    rule(
        Games,
        Publisher,
        PUBLISHER,
        &[
            "blizzard",
            "valve",
            "riot games",
            "electronic arts",
            "ea games",
            "ea sports",
            "ubisoft",
            "epic games",
            "rockstar games",
            "bethesda",
            "cd projekt",
            "mihoyo",
            "hoyoverse",
            "cognosphere",
            "wargaming",
            "activision",
            "2k games",
            "square enix",
            "bandai namco",
            "capcom",
            "gaijin",
            "larian",
            "warhorse",
        ],
    ),
    rule(
        Games,
        Path,
        INSTALL_TREE,
        &[
            r"\steamapps\",
            r"\battle.net\",
            r"\epic games\",
            r"\riot games\",
            r"\gog galaxy\",
            r"\ea games\",
            r"\origin games\",
            r"\ubisoft\",
            r"\rockstar games\",
            r"\wargaming.net\",
            r"\hoyoplay\",
            r"\mihoyo\",
        ],
    ),
    rule(Games, ExeEq, EXE, &["wow", "battle.net"]),
    rule(
        Games,
        Desc,
        DESC,
        &[
            "godot engine",
            "unreal engine",
            "gamemaker",
            "game maker",
            "rpg maker",
            "ren'py",
            "renpy",
        ],
    ),
    rule(
        Games,
        Product,
        PRODUCT,
        &["godot engine", "unreal engine", "gamemaker", "rpg maker"],
    ),
    rule(Games, Path, PATH, &[r"\games\"]),
    rule(
        Games,
        Name,
        NAME,
        &[
            "steam",
            "battle.net",
            "epic games",
            "gog",
            "game",
            "minecraft",
            "roblox",
            "backpack battles",
            "warcraft",
            "hearthstone",
            "dota",
            "valorant",
            "league of legends",
            "apex legends",
            "fortnite",
            "grand theft auto",
            "gta",
            "witcher",
            "cyberpunk",
            "overwatch",
            "diablo",
            "starcraft",
            "genshin",
            "honkai",
            "counter-strike",
            "cs2",
            "csgo",
            "pubg",
            "terraria",
            "stardew",
            "elden ring",
            "dark souls",
            "baldur",
            "warframe",
            "path of exile",
            "dead by daylight",
            "rainbow six",
            "call of duty",
            "warzone",
            "battlefield",
            "world of tanks",
            "war thunder",
            "palworld",
            "valheim",
            "clash of clans",
            "clash royale",
        ],
    ),
    rule(Ai, Publisher, PUBLISHER, &["openai", "anthropic"]),
    rule(
        Ai,
        Name,
        NAME,
        &[
            "claude",
            "chatgpt",
            "openai",
            "codex",
            "ollama",
            "lm studio",
            "gemini",
            "copilot",
            "cursor",
            "ai agent",
            "perplexity",
            "mistral",
            "anythingllm",
            "msty",
            "opencode",
            "aider",
            "cline",
            "roo code",
        ],
    ),
    rule(
        Ai,
        ExeEq,
        EXE,
        &[
            "claude", "chatgpt", "codex", "ollama", "cursor", "opencode", "msty", "aider",
        ],
    ),
    rule(
        Development,
        Publisher,
        PUBLISHER,
        &["jetbrains", "docker, inc", "gitkraken", "mongodb"],
    ),
    rule(
        Development,
        Name,
        NAME,
        &[
            "visual studio",
            "vscode",
            "code",
            "rustrover",
            "pycharm",
            "webstorm",
            "intellij",
            "android studio",
            "git",
            "github",
            "docker",
            "postman",
            "terminal",
            "sublime text",
            "notepad++",
            "node.js",
            "nodejs",
            "python",
            "github desktop",
            "sourcetree",
            "gitkraken",
            "dbeaver",
            "tableplus",
            "heidisql",
            "insomnia",
            "clion",
            "datagrip",
            "phpstorm",
            "cmake",
            "mongodb",
            "studio 3t",
            "robo 3t",
            "dbgate",
            "beekeeper",
        ],
    ),
    rule(Development, ExeContains, EXE_GLUE, &["devhome"]),
    rule(
        Development,
        ExeEq,
        EXE,
        &[
            "devenv",
            "code",
            "rustrover",
            "pycharm64",
            "webstorm64",
            "idea64",
            "postman",
            "rustc",
            "tclsh",
            "wish",
            "mintty",
            "iconv",
            "curl",
            "openssl",
            "stackbuilder",
        ],
    ),
    rule(
        Editors,
        Publisher,
        PUBLISHER,
        &["adobe", "maxon", "blackmagic", "affinity", "corel"],
    ),
    rule(
        Productivity,
        Name,
        DECISIVE,
        &["adobe reader", "acrobat reader"],
    ),
    rule(
        Editors,
        Name,
        NAME,
        &[
            "photoshop",
            "illustrator",
            "lightroom",
            "figma",
            "gimp",
            "inkscape",
            "blender",
            "paint.net",
            "canva",
            "davinci resolve",
            "premiere",
            "after effects",
            "affinity",
            "krita",
            "clip studio",
            "capcut",
            "darktable",
        ],
    ),
    rule(
        Editors,
        ExeEq,
        EXE,
        &[
            "photoshop",
            "illustrator",
            "gimp",
            "blender",
            "krita",
            "inkscape",
        ],
    ),
    rule(
        Productivity,
        ExeContains,
        DECISIVE,
        &["acrord32", "acrobat"],
    ),
    rule(
        Productivity,
        Path,
        INSTALL_TREE,
        &[
            r"\microsoft office",
            r"\microsoft\office\",
            "microsoft.office.",
            r"\libreoffice\",
            r"\onlyoffice\",
            r"\wps office\",
        ],
    ),
    rule(
        Productivity,
        Product,
        PRODUCT,
        &[
            "notion",
            "obsidian",
            "evernote",
            "libreoffice",
            "microsoft office",
        ],
    ),
    rule(
        Productivity,
        Name,
        NAME,
        &[
            "microsoft office",
            "word",
            "winword",
            "excel",
            "powerpnt",
            "onenote",
            "outlook",
            "libreoffice",
            "openoffice",
            "onlyoffice",
            "wps office",
            "notion",
            "obsidian",
            "evernote",
            "joplin",
            "logseq",
            "acrobat",
            "acrord32",
            "foxit",
            "sumatra",
            "pdf-xchange",
            "calibre",
            "zotero",
            "anki",
        ],
    ),
    rule(
        Productivity,
        ExeEq,
        EXE,
        &[
            "winword", "excel", "powerpnt", "onenote", "outlook", "scalc", "swriter", "simpress",
        ],
    ),
    rule(Browsers, Publisher, PUBLISHER, &["mozilla"]),
    rule(
        Browsers,
        Path,
        INSTALL_TREE,
        &[
            r"\mozilla firefox\",
            r"\google\chrome\",
            r"\microsoft\edge\",
        ],
    ),
    rule(
        Browsers,
        Name,
        NAME,
        &[
            "chrome", "firefox", "edge", "opera", "brave", "vivaldi", "browser", "yandex",
            "chromium", "thorium",
        ],
    ),
    rule(
        Browsers,
        ExeEq,
        EXE,
        &[
            "chrome", "firefox", "msedge", "opera", "brave", "vivaldi", "chromium",
        ],
    ),
    rule(Media, Publisher, PUBLISHER, &["videolan", "spotify"]),
    rule(
        Media,
        Name,
        NAME,
        &[
            "vlc",
            "spotify",
            "foobar",
            "audacity",
            "obs",
            "media player",
            "potplayer",
            "mpc-hc",
            "mpc-be",
            "kmplayer",
            "aimp",
            "winamp",
            "itunes",
            "plex",
            "kodi",
            "deezer",
            "tidal",
            "jellyfin",
        ],
    ),
    rule(
        Media,
        ExeEq,
        EXE,
        &[
            "vlc",
            "spotify",
            "foobar2000",
            "audacity",
            "potplayer",
            "aimp",
            "winamp",
            "itunes",
        ],
    ),
    rule(
        Media,
        Name,
        NAME,
        &[
            "музыка",
            "медиаплеер",
            "плеер",
            "видео",
            "кино",
            "фильмы",
            "радио",
        ],
    ),
    rule(
        Communication,
        Name,
        NAME,
        &["почта", "сообщения", "звонки", "мессенджер"],
    ),
    rule(Browsers, Name, NAME, &["браузер", "обозреватель"]),
    rule(
        FileCloud,
        Name,
        NAME,
        &["облако", "диск", "хранилище", "архиватор"],
    ),
    rule(Security, Name, NAME, &["антивирус", "защитник"]),
    rule(
        Productivity,
        Name,
        NAME,
        &["заметки", "календарь", "задачи", "документы", "таблицы"],
    ),
    rule(
        Development,
        Name,
        NAME,
        &[
            "разработка",
            "программирование",
            "среда разработки",
            "компилятор",
        ],
    ),
    rule(
        Editors,
        Name,
        NAME,
        &[
            "редактор",
            "фоторедактор",
            "видеоредактор",
            "монтаж",
            "графика",
        ],
    ),
    rule(
        Games,
        Name,
        NAME,
        &["игра", "игры", "игровой", "лаунчер игр"],
    ),
    rule(
        Ai,
        Name,
        NAME,
        &[
            "нейросеть",
            "нейронка",
            "ассистент ии",
            "искусственный интеллект",
        ],
    ),
    rule(
        Utilities,
        Name,
        NAME,
        &["буфер обмена", "скриншот", "конвертер"],
    ),
    rule(
        Communication,
        Publisher,
        PUBLISHER,
        &["telegram", "whatsapp", "discord inc"],
    ),
    rule(
        Communication,
        Name,
        NAME,
        &[
            "discord",
            "telegram",
            "whatsapp",
            "slack",
            "teams",
            "zoom",
            "skype",
            "signal",
            "viber",
            "wechat",
            "element",
            "thunderbird",
        ],
    ),
    rule(
        Communication,
        ExeEq,
        EXE,
        &[
            "discord",
            "telegram",
            "whatsapp",
            "slack",
            "zoom",
            "skype",
            "thunderbird",
        ],
    ),
    rule(
        FileCloud,
        Name,
        NAME,
        &[
            "7-zip",
            "winrar",
            "peazip",
            "bandizip",
            "nanazip",
            "onedrive",
            "dropbox",
            "google drive",
            "yandex disk",
            "mega",
            "nextcloud",
            "syncthing",
            "total commander",
            "everything",
            "filezilla",
            "winscp",
        ],
    ),
    rule(
        FileCloud,
        ExeEq,
        EXE,
        &[
            "winrar",
            "7zfm",
            "peazip",
            "bandizip",
            "nanazip",
            "dropbox",
            "onedrive",
            "filezilla",
            "winscp",
            "totalcmd64",
        ],
    ),
    rule(
        Security,
        Publisher,
        PUBLISHER,
        &[
            "kaspersky",
            "bitdefender",
            "malwarebytes",
            "eset",
            "avast",
            "avg technologies",
            "doctor web",
            "avira",
            "sophos",
            "trend micro",
            "f-secure",
            "emsisoft",
            "sentinelone",
            "crowdstrike",
        ],
    ),
    rule(
        Security,
        Name,
        NAME,
        &[
            "antivirus",
            "anti-virus",
            "antimalware",
            "anti-malware",
            "endpoint security",
            "internet security",
            "kaspersky",
            "bitdefender",
            "malwarebytes",
            "eset",
            "avast",
            "norton",
            "mcafee",
            "drweb",
            "dr.web",
            "keepass",
            "bitwarden",
            "1password",
            "dashlane",
            "nordpass",
            "proton pass",
            "vpn",
            "proxy",
            "wireguard",
            "openvpn",
            "hiddify",
            "nekoray",
            "nekobox",
            "clash verge",
            "clashx",
            "mihomo",
            "v2ray",
            "xray",
            "sing-box",
            "shadowsocks",
            "outline",
            "cloudflare warp",
            "mullvad",
            "proton vpn",
            "nordvpn",
            "expressvpn",
            "surfshark",
            "windscribe",
            "ipvanish",
            "tunnelbear",
            "psiphon",
            "w10privacy",
            "shutup10",
            "privatezilla",
            "simplewall",
        ],
    ),
    rule(Security, ExeContains, EXE_GLUE, &["vpn", "proxy"]),
    rule(
        Utilities,
        Name,
        NAME,
        &[
            "powertoys",
            "rufus",
            "verifier",
            "configure",
            "utility",
            "uninstaller",
            "cpu-z",
            "gpu-z",
            "hwinfo",
            "hwmonitor",
            "crystaldiskinfo",
            "crystaldiskmark",
            "hard disk sentinel",
            "hdsentinel",
            "hdsentineltray",
            "low level format",
            "hd tune",
            "aida64",
            "msi afterburner",
            "rivatuner",
            "treesize",
            "windirstat",
            "ccleaner",
            "revo uninstaller",
            "display driver uninstaller",
            "victoria",
            "memtest",
            "furmark",
            "winmtr",
        ],
    ),
    rule(
        Games,
        Name,
        NAME,
        &[
            "xbox",
            "curseforge",
            "playnite",
            "ea app",
            "gog galaxy",
            "riot client",
            "faceit",
            "geforce now",
            "amazon games",
            "ubisoft connect",
            "rockstar games launcher",
            "modrinth",
            "prism launcher",
            "atlauncher",
            "multimc",
            "vortex",
            "playstation",
            "epic games launcher",
        ],
    ),
    rule(Ai, Publisher, PUBLISHER, &["mistral ai", "perplexity"]),
    rule(
        Ai,
        Name,
        NAME,
        &[
            "codeium",
            "windsurf",
            "gpt4all",
            "deepseek",
            "tabnine",
            "librechat",
            "comfyui",
            "fooocus",
            "invokeai",
            "pinokio",
            "automatic1111",
            "stable diffusion",
            "kobold",
            "jan.ai",
        ],
    ),
    rule(
        Development,
        Publisher,
        PUBLISHER,
        &[
            "postgresql",
            "python software foundation",
            "hashicorp",
            "atlassian",
            "the qt company",
            "espressif",
        ],
    ),
    rule(
        Development,
        Name,
        NAME,
        &[
            "vscodium",
            "zed",
            "neovim",
            "goland",
            "rider",
            "deno",
            "bun",
            "pnpm",
            "rustup",
            "cargo",
            "anaconda",
            "miniconda",
            "jupyter",
            "spyder",
            "rstudio",
            "matlab",
            "arduino",
            "platformio",
            "kicad",
            "docker desktop",
            "podman",
            "terraform",
            "vagrant",
            "ngrok",
            "bruno",
            "mysql",
            "mariadb",
            "postgresql",
            "postgres",
            "pgadmin",
            "navicat",
            "sqlitestudio",
            "azure data studio",
            "mongodb compass",
            "redisinsight",
            "wezterm",
            "alacritty",
            "tabby",
            "mobaxterm",
            "putty",
            "termius",
            "tortoisegit",
            "tortoisesvn",
            "smartgit",
            "sublime merge",
            "winmerge",
            "beyond compare",
            "eclipse",
            "netbeans",
            "qt creator",
            "ghidra",
            "x64dbg",
            "wireshark",
            "java",
            "jdk",
            "openjdk",
            "temurin",
            "dotnet",
            "xampp",
            "laragon",
            "psql",
            "dev home",
            "wsl settings",
            "certification kit",
            "llvm",
            "vsce",
            "rust compiler",
            "stack builder",
            "developer command prompt",
            "developer powershell",
            "debuggable package manager",
        ],
    ),
    rule(
        Editors,
        Publisher,
        PUBLISHER,
        &[
            "autodesk",
            "wondershare",
            "techsmith",
            "topaz labs",
            "skylum",
        ],
    ),
    rule(
        Editors,
        Name,
        NAME,
        &[
            "clipchamp",
            "shotcut",
            "kdenlive",
            "handbrake",
            "filmora",
            "camtasia",
            "vegas pro",
            "photopea",
            "aseprite",
            "autocad",
            "fusion 360",
            "sketchup",
            "coreldraw",
            "acdsee",
            "irfanview",
            "xnview",
            "faststone",
            "imageglass",
            "zbrush",
            "cinema 4d",
            "solidworks",
            "freecad",
        ],
    ),
    rule(
        Productivity,
        Publisher,
        PUBLISHER,
        &["the document foundation", "kingsoft"],
    ),
    rule(
        Productivity,
        Name,
        NAME,
        &[
            "powerpoint",
            "visio",
            "todoist",
            "ticktick",
            "microsoft to do",
            "grammarly",
            "deepl",
            "xmind",
            "typora",
            "okular",
            "sumatrapdf",
            "pdf24",
            "pdfsam",
            "trello",
            "clickup",
            "confluence",
            "anytype",
            "goodnotes",
            "apple books",
            "google keep",
            "power automate",
        ],
    ),
    rule(
        Browsers,
        Publisher,
        PUBLISHER,
        &["brave software", "the tor project"],
    ),
    rule(
        Browsers,
        Name,
        NAME,
        &[
            "tor browser",
            "waterfox",
            "librewolf",
            "pale moon",
            "maxthon",
            "floorp",
            "zen browser",
            "opera gx",
            "mullvad browser",
            "comodo dragon",
        ],
    ),
    rule(
        Media,
        Publisher,
        PUBLISHER,
        &["image-line", "ableton", "native instruments", "steinberg"],
    ),
    rule(
        Media,
        Name,
        NAME,
        &[
            "mpv",
            "musicbee",
            "clementine",
            "strawberry",
            "stremio",
            "emby",
            "youtube music",
            "soundcloud",
            "groove music",
            "apple music",
            "mediamonkey",
            "reaper",
            "fl studio",
            "ableton",
            "cubase",
            "studio one",
            "cakewalk",
            "lmms",
            "mixxx",
            "virtual dj",
            "rekordbox",
            "obs studio",
            "streamlabs",
            "xsplit",
        ],
    ),
    rule(
        Communication,
        Name,
        NAME,
        &[
            "microsoft teams",
            "webex",
            "jitsi",
            "mattermost",
            "threema",
            "kakaotalk",
            "messenger",
            "ferdium",
            "mailbird",
            "em client",
            "proton mail",
            "tutanota",
            "mailspring",
            "teamspeak",
            "mumble",
        ],
    ),
    rule(
        FileCloud,
        Name,
        NAME,
        &[
            "utorrent",
            "bittorrent",
            "qbittorrent",
            "transmission",
            "deluge",
            "picotorrent",
            "winzip",
            "teracopy",
            "fastcopy",
            "freefilesync",
            "icloud",
            "pcloud",
            "rclone",
            "cyberduck",
            "xyplorer",
            "directory opus",
            "freecommander",
            "double commander",
            "duplicati",
            "macrium reflect",
            "aomei backupper",
            "ventoy",
            "balenaetcher",
            "poweriso",
            "ultraiso",
            "daemon tools",
            "wiztree",
            "spacesniffer",
        ],
    ),
    rule(
        Security,
        Publisher,
        PUBLISHER,
        &["avira", "sophos", "f-secure"],
    ),
    rule(
        Security,
        Name,
        NAME,
        &[
            "avira",
            "sophos",
            "f-secure",
            "adguard",
            "adwcleaner",
            "hitmanpro",
            "glasswire",
            "tailscale",
            "zerotier",
            "softether",
            "veracrypt",
            "cryptomator",
            "axcrypt",
            "keepassxc",
            "enpass",
            "authy",
            "2fas",
            "gpg4win",
            "kleopatra",
        ],
    ),
    rule(
        Utilities,
        Publisher,
        PUBLISHER,
        &[
            "nvidia",
            "advanced micro devices",
            "realtek",
            "logitech",
            "razer",
            "corsair",
            "steelseries",
            "micro-star",
            "asustek",
            "gigabyte",
            "sysinternals",
            "nirsoft",
            "piriform",
            "geeks3d",
            "crystal dew world",
            "sordum",
            "сафиб",
        ],
    ),
    rule(Media, Name, DECISIVE, &["nvidia broadcast"]),
    rule(
        Utilities,
        Name,
        NAME,
        &[
            "nvidia app",
            "geforce experience",
            "amd software",
            "radeon software",
            "msi center",
            "armoury crate",
            "aura sync",
            "icue",
            "razer synapse",
            "steelseries gg",
            "openrgb",
            "signalrgb",
            "logi options",
            "g hub",
            "fan control",
            "core temp",
            "throttlestop",
            "ryzen master",
            "cinebench",
            "3dmark",
            "occt",
            "prime95",
            "autoruns",
            "process explorer",
            "process hacker",
            "system informer",
            "autohotkey",
            "autoit",
            "sharex",
            "greenshot",
            "lightshot",
            "flameshot",
            "snagit",
            "teamviewer",
            "anydesk",
            "rustdesk",
            "tightvnc",
            "realvnc",
            "parsec",
            "moonlight",
            "listary",
            "flow launcher",
            "rainmeter",
            "wallpaper engine",
            "displayfusion",
            "translucenttb",
            "ditto",
            "bulk crap uninstaller",
            "iobit uninstaller",
            "chocolatey",
            "scoop",
            "ninite",
            "windows update blocker",
            "windhawk",
            "startallback",
            "explorerpatcher",
            "open shell",
            "classic shell",
            "attack shark",
            "aladdin hasp",
            "rtsshooksloader",
            "aula f75",
            "устройства apple",
            "apple devices",
            "overclocking scanner",
        ],
    ),
    rule(
        Utilities,
        ExeContains,
        EXE_GLUE,
        &["rtss", "sharedmemorysample", "dataprovider", "overlayhost"],
    ),
    rule(Utilities, Publisher, PUBLISHER, &["keskiyo"]),
    rule(Productivity, Path, PATH, OFFICE_INSTALLER_FAMILIES),
    rule(Productivity, Name, NAME, &["office", "poster printer"]),
    rule(Utilities, Path, PATH, &[r"\totalcmd"]),
    rule(Utilities, Name, NAME, &["ip scanner", "naps2", "twain"]),
    rule(Security, Path, PATH, &[r"\crypto pro"]),
    rule(Security, Name, NAME, &["криптопро"]),
    rule(Editors, Name, NAME, &["abbyy"]),
    rule(Development, Path, PATH, &[r"\windows kits\"]),
    rule(System, Path, PATH, &[r"\start menu\programs\system tools"]),
    rule(Communication, Name, NAME, &["trueconf"]),
    rule(
        Communication,
        Publisher,
        PUBLISHER,
        &["communication platform"],
    ),
    rule(Security, Path, PATH, &["vpn", "proxy"]),
    rule(
        Media,
        Name,
        NAME,
        &["yt-dlp", "youtube downloader", "video downloader"],
    ),
    rule(
        Security,
        Name,
        NAME,
        &["firewall", "security configuration"],
    ),
    rule(
        Utilities,
        Name,
        NAME,
        &["nvidia control", "audio console", "frameview"],
    ),
    rule(
        Development,
        Name,
        NAME,
        &["wsl", "ubuntu", "native tools", "cross tools"],
    ),
    rule(Utilities, NameEq, NAME, &["windows apps"]),
    rule(Productivity, Publisher, PUBLISHER, &["1с-софт", "1c-soft"]),
    rule(Productivity, Product, PRODUCT, &["1с предприятие"]),
    rule(Productivity, Path, PATH, &[r"\1cv8\"]),
    rule(Productivity, Name, NAME, &["draw.io"]),
    rule(
        Development,
        Name,
        NAME,
        &["cheat engine", "firebird", "interbase"],
    ),
    rule(Development, Path, PATH, &[r"\cheat engine", r"\firebird\"]),
    rule(Media, Name, NAME, &["equalizer apo", "magicmic"]),
    rule(Media, Path, PATH, &[r"\equalizerapo"]),
    rule(Games, Name, NAME, &["overwolf", "gryphlink"]),
    rule(
        Utilities,
        Publisher,
        PUBLISHER,
        &["deepcool", "lamzu", "creative labs", "safenet"],
    ),
    rule(Utilities, Name, NAME, &["geforce", "lagofast", "openal"]),
    rule(Utilities, ExeEq, EXE, &["yandexpin", "haspdinst"]),
    rule(WindowsFeatures, NameEq, FEATURE, WINDOWS_FEATURE_NAMES),
    rule(WindowsFeatures, ExeEq, FEATURE, WINDOWS_FEATURE_EXECUTABLES),
    rule(WindowsFeatures, Path, FEATURE, WINDOWS_FEATURE_PACKAGES),
    rule(
        System,
        Name,
        NAME,
        &[
            "partition wizard",
            "partition assistant",
            "partition master",
            "disk director",
            "virtualbox",
            "vmware",
            "hyper-v",
            "bootable usb",
            "виртуальная машина",
            "менеджер разделов",
            "резервная копия",
            "образ системы",
        ],
    ),
    rule(
        System,
        ExeEq,
        EXE,
        &["virtualbox", "vmware", "vmplayer", "truimage", "reflect"],
    ),
    rule(
        System,
        Publisher,
        PUBLISHER,
        &["acronis", "veeam", "paragon software", "minitool"],
    ),
    rule(Games, Path, PATH, &[r"\игры\"]),
    rule(Editors, Path, PATH, &[r"\graphics\", r"\графика\"]),
    rule(
        Development,
        Path,
        PATH,
        &[r"\development\", r"\разработка\", r"\программирование\"],
    ),
    rule(
        Utilities,
        Path,
        PATH,
        &[
            r"\utilities\",
            r"\служебные\",
            r"\accessories\",
            r"\стандартные\",
        ],
    ),
    rule(Media, Path, PATH, &[r"\мультимедиа\", r"\multimedia\"]),
    rule(Media, Association, EXE, vocabulary::MEDIA_ASSOCIATIONS),
    rule(Editors, Association, EXE, vocabulary::EDITORS_ASSOCIATIONS),
    rule(
        Development,
        Association,
        EXE,
        vocabulary::DEVELOPMENT_ASSOCIATIONS,
    ),
    rule(
        FileCloud,
        Association,
        EXE,
        vocabulary::FILE_CLOUD_ASSOCIATIONS,
    ),
    rule(
        Productivity,
        Association,
        EXE,
        vocabulary::PRODUCTIVITY_ASSOCIATIONS,
    ),
    rule(
        Browsers,
        Association,
        EXE,
        vocabulary::BROWSERS_ASSOCIATIONS,
    ),
    rule(
        Communication,
        Association,
        EXE,
        vocabulary::COMMUNICATION_ASSOCIATIONS,
    ),
    rule(Games, Association, EXE, vocabulary::GAMES_ASSOCIATIONS),
    rule(System, Association, EXE, vocabulary::SYSTEM_ASSOCIATIONS),
    rule(Media, Desc, VOCABULARY, vocabulary::MEDIA),
    rule(Media, Product, VOCABULARY, vocabulary::MEDIA),
    rule(Browsers, Desc, VOCABULARY, vocabulary::BROWSERS),
    rule(Browsers, Product, VOCABULARY, vocabulary::BROWSERS),
    rule(Communication, Desc, VOCABULARY, vocabulary::COMMUNICATION),
    rule(
        Communication,
        Product,
        VOCABULARY,
        vocabulary::COMMUNICATION,
    ),
    rule(Development, Desc, VOCABULARY, vocabulary::DEVELOPMENT),
    rule(Development, Product, VOCABULARY, vocabulary::DEVELOPMENT),
    rule(Editors, Desc, VOCABULARY, vocabulary::EDITORS),
    rule(Editors, Product, VOCABULARY, vocabulary::EDITORS),
    rule(Games, Desc, VOCABULARY, vocabulary::GAMES),
    rule(Games, Product, VOCABULARY, vocabulary::GAMES),
    rule(Security, Desc, VOCABULARY, vocabulary::SECURITY),
    rule(Security, Product, VOCABULARY, vocabulary::SECURITY),
    rule(FileCloud, Desc, VOCABULARY, vocabulary::FILE_CLOUD),
    rule(FileCloud, Product, VOCABULARY, vocabulary::FILE_CLOUD),
    rule(Productivity, Desc, VOCABULARY, vocabulary::PRODUCTIVITY),
    rule(Productivity, Product, VOCABULARY, vocabulary::PRODUCTIVITY),
    rule(Utilities, Desc, VOCABULARY, vocabulary::UTILITIES),
    rule(Utilities, Product, VOCABULARY, vocabulary::UTILITIES),
    rule(Ai, Desc, VOCABULARY, vocabulary::AI),
    rule(Ai, Product, VOCABULARY, vocabulary::AI),
    rule(System, Desc, VOCABULARY, vocabulary::SYSTEM),
    rule(System, Product, VOCABULARY, vocabulary::SYSTEM),
];

static WINDOWS_FEATURE_NAMES: &[&str] = &[
    "этот компьютер",
    "file explorer",
    "проводник",
    "snipping tool",
    "ножницы",
    "get help",
    "техническая поддержка",
    "remote desktop connection",
    "подключение к удаленному рабочему столу",
    "calculator",
    "калькулятор",
    "notepad",
    "блокнот",
    "microsoft paint",
    "камера",
    "clock",
    "часы",
    "voice recorder",
    "sound recorder",
    "запись голоса",
    "звукозапись",
    "magnifier",
    "экранная лупа",
    "on-screen keyboard",
    "экранная клавиатура",
    "narrator",
    "экранный диктор",
    "quick assist",
    "быстрая помощь",
    "windows security",
    "безопасность windows",
    "windows settings",
    "параметры",
    "инструменты windows",
    "windows backup",
    "windowsbackup",
    "архивация windows",
    "microsoft store",
    "фотографии",
    "погода",
    "новости",
    "sticky notes",
    "записки",
    "phone link",
    "связь с телефоном",
    "feedback hub",
    "центр отзывов",
    "выполнить",
    "windows media player legacy",
    "steps recorder",
    "средство записи действий",
    "memory diagnostics tool",
    "средство проверки памяти windows",
    "recoverydrive",
    "диск восстановления",
    "iscsi initiator",
    "инициатор iscsi",
    "computer management",
    "управление компьютером",
    "print management",
    "управление печатью",
    "device manager",
    "диспетчер устройств",
    "disk management",
    "управление дисками",
    "event viewer",
    "просмотр событий",
    "task scheduler",
    "планировщик задач",
    "планировщик заданий",
    "local security policy",
    "локальная политика безопасности",
    "group policy",
    "групповая политика",
    "system configuration",
    "конфигурация системы",
    "resource monitor",
    "монитор ресурсов",
    "performance monitor",
    "системный монитор",
    "component services",
    "службы компонентов",
    "odbc data sources",
    "источники данных odbc",
    "system information",
    "сведения о системе",
    "control panel",
    "панель управления",
    "administrative tools",
    "windows tools",
    "администрирование",
    "средства windows",
    "registry editor",
    "редактор реестра",
    "disk cleanup",
    "очистка диска",
    "defragment",
    "дефрагментация",
    "windows defender firewall",
    "брандмауэр",
    "system restore",
    "восстановление системы",
    "службы",
    "character map",
    "таблица символов",
    "command prompt",
    "командная строка",
    "windows powershell",
    "windows powershell ise",
    "windows terminal",
    "task manager",
    "диспетчер задач",
    "optimize drives",
    "defragment and optimize drives",
    "оптимизация дисков",
    "voice access",
    "голосовой доступ",
    "get started",
    "начало работы",
    "live captions",
    "автоматические субтитры",
    "click to do",
    "действие щелчком",
];

static WINDOWS_FEATURE_EXECUTABLES: &[&str] = &[
    "snippingtool",
    "livecaptions",
    "clicktodo",
    "familyhub",
    "voiceaccess",
    "mstsc",
    "mspaint",
    "magnify",
    "osk",
    "narrator",
    "systemsettings",
    "psr",
    "mdsched",
    "recoverydrive",
    "iscsicpl",
    "compmgmt",
    "printmanagement",
    "devmgmt",
    "diskmgmt",
    "eventvwr",
    "taskschd",
    "secpol",
    "gpedit",
    "msconfig",
    "resmon",
    "perfmon",
    "comexp",
    "odbcad32",
    "msinfo32",
    "control",
    "regedit",
    "cleanmgr",
    "dfrgui",
    "wf",
    "rstrui",
    "services",
    "charmap",
    "cmd",
    "powershell",
    "taskmgr",
];

static WINDOWS_FEATURE_PACKAGES: &[&str] = &[
    "microsoft.screensketch",
    "microsoft.gethelp",
    "microsoft.windowscalculator",
    "microsoft.windowsnotepad",
    "microsoft.paint",
    "microsoft.windowscamera",
    "microsoft.windowsalarms",
    "microsoft.windowssoundrecorder",
    "microsoftcorporationii.quickassist",
    "microsoft.sechealthui",
    "microsoft.windows.administrativetools",
    "microsoft.windowsstore",
    "microsoft.windows.photos",
    "microsoft.bingweather",
    "microsoft.bingnews",
    "microsoft.windowsmaps",
    "microsoft.m365companions",
    "microsoft.microsoftstickynotes",
    "microsoft.yourphone",
    "microsoft.windowsfeedbackhub",
    "microsoft.windows.shell.rundialog",
    "microsoft.windowsterminal",
    "_cw5n1h2txyewy",
    r"\windows\systemapps\",
    r"\windows\system32",
    r"\windows\syswow64",
    r"\windows\speech",
];

static OFFICE_INSTALLER_FAMILIES: &[&str] = &[
    r"\installer\{90120000",
    r"\installer\{90140000",
    r"\installer\{90150000",
    r"\installer\{90160000",
];

#[cfg(test)]
mod tests {
    use super::super::super::AppCategory::WindowsFeatures;
    use super::RULES;

    const PACKAGING_PUBLISHERS: &[&str] = &[
        "github, inc",
        "electron",
        "nullsoft",
        "nsis",
        "inno setup",
        "squirrel",
    ];

    fn identifies_a_product(field: &str) -> bool {
        matches!(field, "name" | "product" | "exe")
    }

    #[test]
    fn no_publisher_rule_reads_a_packaging_default_as_purpose() {
        let mut borrowed = Vec::new();
        for rule in RULES.iter().filter(|rule| rule.field.id() == "publisher") {
            for needle in rule.needles {
                if PACKAGING_PUBLISHERS.contains(&needle.trim_end_matches('.')) {
                    borrowed.push(format!(
                        "{:?} claims packaging default {needle:?}",
                        rule.category
                    ));
                }
            }
        }

        assert_eq!(borrowed, Vec::<String>::new());
    }

    #[test]
    fn a_windows_feature_is_recognised_by_a_whole_value_never_a_substring() {
        let loose: Vec<String> = RULES
            .iter()
            .filter(|rule| rule.category == WindowsFeatures)
            .filter(|rule| !rule.field.is_whole_value() && rule.field.id() != "path")
            .map(|rule| format!("matched by {} as a substring", rule.field.id()))
            .collect();

        assert_eq!(loose, Vec::<String>::new());
    }

    const TRANSLITERATION: &[(char, &str)] = &[
        ('а', "a"),
        ('б', "b"),
        ('в', "v"),
        ('г', "g"),
        ('д', "d"),
        ('е', "e"),
        ('ё', "e"),
        ('ж', "zh"),
        ('з', "z"),
        ('и', "i"),
        ('й', "y"),
        ('к', "k"),
        ('л', "l"),
        ('м', "m"),
        ('н', "n"),
        ('о', "o"),
        ('п', "p"),
        ('р', "r"),
        ('с', "s"),
        ('т', "t"),
        ('у', "u"),
        ('ф', "f"),
        ('х', "h"),
        ('ц', "ts"),
        ('ч', "ch"),
        ('ш', "sh"),
        ('щ', "sch"),
        ('ъ', ""),
        ('ы', "y"),
        ('ь', ""),
        ('э', "e"),
        ('ю', "yu"),
        ('я', "ya"),
    ];

    fn transliterate(value: &str) -> Option<String> {
        let mut changed = false;
        let latin: String = value
            .chars()
            .map(|character| {
                match TRANSLITERATION
                    .iter()
                    .find(|(cyrillic, _)| *cyrillic == character)
                {
                    Some((_, latin)) => {
                        changed = true;
                        (*latin).to_owned()
                    }
                    None => character.to_string(),
                }
            })
            .collect();
        changed.then_some(latin)
    }

    #[test]
    fn a_localised_needle_does_not_collide_with_another_category_transliterated() {
        let mut collisions = Vec::new();
        for rule in RULES.iter().filter(|r| identifies_a_product(r.field.id())) {
            for needle in rule.needles {
                let Some(latin) = transliterate(needle) else {
                    continue;
                };
                for other in RULES
                    .iter()
                    .filter(|r| identifies_a_product(r.field.id()))
                    .filter(|r| r.category != rule.category)
                {
                    if other.needles.contains(&latin.as_str()) {
                        collisions.push(format!(
                            "{needle:?} in {:?} transliterates to {latin:?} in {:?}",
                            rule.category, other.category
                        ));
                    }
                }
            }
        }

        assert_eq!(collisions, Vec::<String>::new());
    }

    #[test]
    fn no_product_needle_is_claimed_by_two_categories() {
        let mut contested = Vec::new();
        for (index, left) in RULES.iter().enumerate() {
            if !identifies_a_product(left.field.id()) {
                continue;
            }
            for right in RULES
                .iter()
                .skip(index + 1)
                .filter(|rule| identifies_a_product(rule.field.id()))
                .filter(|rule| rule.category != left.category)
            {
                for needle in left.needles {
                    if right.needles.contains(needle) {
                        contested.push(format!(
                            "{needle:?} claimed by {:?} and {:?}",
                            left.category, right.category
                        ));
                    }
                }
            }
        }

        assert_eq!(contested, Vec::<String>::new());
    }

    #[test]
    fn a_vendor_publisher_never_outranks_a_product_another_category_names() {
        let mut unreachable = Vec::new();
        for vendor in RULES.iter().filter(|rule| rule.field.id() == "publisher") {
            for product in RULES
                .iter()
                .filter(|rule| identifies_a_product(rule.field.id()))
                .filter(|rule| rule.category != vendor.category)
                .filter(|rule| rule.weight < vendor.weight)
            {
                for needle in product.needles {
                    if vendor.needles.iter().any(|brand| needle.contains(brand)) {
                        unreachable.push(format!(
                            "{:?} {needle:?} scores {} against {:?} publisher {}",
                            product.category, product.weight, vendor.category, vendor.weight
                        ));
                    }
                }
            }
        }

        assert_eq!(unreachable, Vec::<String>::new());
    }
}
