import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { AppInfoDialog } from '../../../../src/features/view-app-details/ui/AppInfoDialog/AppInfoDialog'
import type { AppDetails, AppInfo } from '../../../../src/entities/app'
import type { CategoryDefinition } from '../../../../src/entities/category'

const app: AppInfo = {
	id: 'example-editor',
	name: 'Example Editor',
	path: 'C:\\Program Files\\Example\\editor.exe',
	iconBase64: null,
	category: 'editors',
	launchKind: 'executable',
	sourceKind: 'registry',
	description: 'An example editor',
	version: '1.2.3',
	publisher: 'Example Corp',
	installLocation: 'C:\\Program Files\\Example',
	canUninstall: false,
}

const categories: CategoryDefinition[] = [
	{ id: 'editors', label: 'Editors', builtIn: true },
]

const details: AppDetails = {
	fileSizeBytes: 1_572_864,
	fileCreatedAt: 0,
	fileModifiedAt: 1_700_000_000,
	architecture: 'x64',
	signature: 'verified',
	executableExists: true,
	installLocationExists: true,
	canOpenFolder: true,
}

const msixApp: AppInfo = {
	...app,
	id: 'contoso.package-app',
	name: 'Contoso Package',
	path: 'Contoso.Package_123!App',
	launchKind: 'app_user_model_id',
	sourceKind: 'msix',
	installLocation: 'C:\\Program Files\\WindowsApps\\Contoso.Package_123',
}

const msixDetails: AppDetails = {
	fileSizeBytes: null,
	fileCreatedAt: null,
	fileModifiedAt: null,
	architecture: 'unknown',
	signature: 'unavailable',
	executableExists: null,
	installLocationExists: null,
}

const systemStartApp: AppInfo = {
	...app,
	id: 'windows-task-scheduler',
	name: 'Task Scheduler',
	path: 'Microsoft.AutoGenerated.{TaskScheduler}',
	launchKind: 'app_user_model_id',
	sourceKind: 'start_apps',
	installLocation: 'C:\\Windows\\System32',
	resolvedPath: 'C:\\Windows\\System32\\taskschd.msc',
}

const systemStartDetails: AppDetails = {
	fileSizeBytes: 145_059,
	fileCreatedAt: 1_711_956_127,
	fileModifiedAt: 1_711_956_127,
	architecture: 'notApplicable',
	signature: 'verified',
	executableExists: true,
	installLocationExists: true,
	canOpenFolder: true,
}

function renderDialog(
	overrides: {
		app?: AppInfo
		details?: AppDetails
		loadFails?: boolean
	} = {},
) {
	const getAppDetails = overrides.loadFails
		? vi.fn().mockRejectedValue(new Error('private path'))
		: vi.fn().mockResolvedValue(overrides.details ?? details)
	const openAppFolder = vi.fn().mockResolvedValue(undefined)
	const onClose = vi.fn()
	render(
		<AppInfoDialog
			app={overrides.app ?? app}
			categories={categories}
			appsClient={{ getAppDetails, openAppFolder }}
			onClose={onClose}
		/>,
	)
	return { getAppDetails, openAppFolder, onClose }
}

afterEach(() => {
	Object.defineProperty(navigator, 'clipboard', {
		configurable: true,
		value: undefined,
	})
})

describe('AppInfoDialog', () => {
	it('loads details, runs information actions and toggles additional information', async () => {
		const user = userEvent.setup()
		const writeText = vi.fn().mockResolvedValue(undefined)
		Object.defineProperty(navigator, 'clipboard', {
			configurable: true,
			value: { writeText },
		})
		const { getAppDetails, openAppFolder } = renderDialog()

		await screen.findByText('Application')
		expect(getAppDetails).toHaveBeenCalledWith(app.id)
		await user.click(
			screen.getByRole('button', { name: 'Additional information' }),
		)
		expect(screen.getByText('1.5 MB')).toBeVisible()
		expect(
			screen.getByRole('button', { name: 'Additional information' }),
		).toHaveAttribute('aria-expanded', 'true')
		await user.click(
			screen.getByRole('button', { name: 'Additional information' }),
		)
		expect(
			screen.getByRole('button', { name: 'Additional information' }),
		).toHaveAttribute('aria-expanded', 'false')
		await user.click(screen.getByRole('button', { name: 'Open folder' }))
		expect(openAppFolder).toHaveBeenCalledWith(app.id)
		await user.click(screen.getByRole('button', { name: 'Copy path' }))
		expect(writeText).toHaveBeenLastCalledWith(app.path)
		await user.click(screen.getByRole('button', { name: 'Copy report' }))
		expect(writeText).toHaveBeenCalledWith(
			expect.not.stringContaining('private path'),
		)
		expect(
			screen.queryByRole('button', { name: 'Launch Example Editor' }),
		).not.toBeInTheDocument()
	})

	it('keeps backend details unavailable without exposing the raw failure', async () => {
		renderDialog({ loadFails: true })

		expect(
			await screen.findByText('Application details are unavailable.'),
		).toBeVisible()
		expect(screen.queryByText('private path')).not.toBeInTheDocument()
	})

	it('uses matched MSIX package metadata for installation status', async () => {
		const user = userEvent.setup()
		renderDialog({ app: msixApp, details: msixDetails })

		const status = await screen.findByRole('heading', { name: 'Status' })
		const card = status.closest('section')
		expect(card).not.toBeNull()
		expect(within(card!).getByText('Yes')).toBeVisible()
		const additional = screen.getByRole('button', {
			name: 'Additional information',
		})
		await user.click(additional)
		expect(
			within(additional.closest('section')!).getByText('Yes'),
		).toBeVisible()
	})

	it('settles unavailable MSIX executable metadata without a perpetual check', async () => {
		const user = userEvent.setup()
		renderDialog({ app: msixApp, details: msixDetails })

		await screen.findAllByText('Not available')
		await user.click(
			screen.getByRole('button', { name: 'Additional information' }),
		)
		expect(screen.queryByText('Checking…')).not.toBeInTheDocument()
		expect(screen.getAllByText('Not available').length).toBeGreaterThan(0)
	})

	it('shows a resolved Windows Start App file target and enables its folder action', async () => {
		renderDialog({ app: systemStartApp, details: systemStartDetails })

		await screen.findByText('Launch target')
		expect(
			screen.getByText('C:\\Windows\\System32\\taskschd.msc'),
		).toBeVisible()
		expect(
			screen.queryByText('Microsoft.AutoGenerated.{TaskScheduler}'),
		).not.toBeInTheDocument()
		const status = screen.getByRole('heading', { name: 'Status' })
		expect(
			within(status.closest('section')!).getByText('Launch target found'),
		).toBeVisible()
		expect(
			screen.getByRole('button', { name: 'Open folder' }),
		).toBeEnabled()
	})

	it('shows the original file name without repeating the launch type', async () => {
		renderDialog({
			app: {
				...app,
				originalFilename: 'example-editor.exe',
			},
		})

		await screen.findByText('Application')
		expect(screen.getByText('Original filename')).toBeVisible()
		expect(screen.getByText('example-editor.exe')).toBeVisible()
		expect(screen.getAllByText('Launch type')).toHaveLength(1)
		expect(screen.queryByText('Method')).not.toBeInTheDocument()
	})

	// "Why is this in Auxiliary tools" and "why was its target not checked" were answers only the
	// source code held. Both are decisions the backend already made and recorded.
	it('explains why an entry was classified the way it was', async () => {
		renderDialog({
			app: {
				...app,
				visibilityClass: 'auxiliary',
				visibilityReasons: ['maintenance_executable'],
				targetAvailability: 'target.unverifiable.access_denied',
			},
		})

		await screen.findByText('Application')
		expect(screen.getByText('Auxiliary tool')).toBeVisible()
		expect(screen.getByText('Why')).toBeVisible()
		expect(screen.getByText('Maintenance executable')).toBeVisible()
		expect(screen.getByText('Launch target check')).toBeVisible()
		expect(screen.getByText('Not checked — access denied')).toBeVisible()
	})

	/// A record from a cache written before the check was recorded has nothing to say about it, and
	/// must not claim the check failed.
	it('says nothing about a launch-target check that was never recorded', async () => {
		renderDialog({ app: { ...app, targetAvailability: undefined } })

		await screen.findByText('Application')
		expect(
			screen.queryByText('Launch target check'),
		).not.toBeInTheDocument()
	})

	// The category is the classification a user actually rearranges, and until now the only place
	// its reason existed was the rule table in the backend source.
	it('explains which signal put the entry in its category', async () => {
		renderDialog({
			app: {
				...app,
				categoryReasons: ['publisher=jetbrains', 'exe=idea'],
			},
		})

		await screen.findByText('Application')
		expect(screen.getByText('Why this category')).toBeVisible()
		expect(
			screen.getByText('publisher “jetbrains”, executable “idea”'),
		).toBeVisible()
	})

	it('says nothing about a category reason that was never recorded', async () => {
		renderDialog({ app: { ...app, categoryReasons: undefined } })

		await screen.findByText('Application')
		expect(screen.queryByText('Why this category')).not.toBeInTheDocument()
	})

	// The reason list is additive on the backend, so a window built before a new identifier existed
	// will be handed one. Dropping it beats printing `sparkle=yes` at the user.
	it('drops a reason identifier it does not recognize', async () => {
		renderDialog({
			app: {
				...app,
				categoryReasons: ['sparkle=yes', 'publisher=jetbrains'],
			},
		})

		await screen.findByText('Application')
		expect(screen.getByText('publisher “jetbrains”')).toBeVisible()
	})
})
