import { describe, expect, it } from 'vitest'
import {
	buildAppReport,
	formatFileDate,
	formatFileSize,
	middleEllipsis,
} from '../../../../src/entities/app/lib/appMetadata'
import type { AppDetails, AppInfo } from '../../../../src/entities/app'

const app: AppInfo = {
	id: 'target:editor',
	name: 'Example Editor',
	path: 'C:\\Program Files\\Example\\editor.exe',
	iconBase64: null,
	category: 'editors',
	launchKind: 'executable',
	sourceKind: 'registry',
	description: 'A test editor',
	version: 'v1.2.3',
	publisher: 'Example Corp',
	productName: 'Example Editor',
	originalFilename: 'editor.exe',
	installLocation: 'C:\\Program Files\\Example',
	canUninstall: true,
	canonicalIdentity: 'registry:private-key',
}

const details: AppDetails = {
	fileSizeBytes: 1_572_864,
	fileCreatedAt: 0,
	fileModifiedAt: 1_700_000_000,
	architecture: 'x64',
	signature: 'verified',
	executableExists: true,
	installLocationExists: true,
}

describe('application metadata presentation', () => {
	it('formats missing, zero and large file values safely', () => {
		expect(formatFileSize(null)).toBe('Not available')
		expect(formatFileSize(0)).toBe('0 B')
		expect(formatFileSize(1_572_864)).toBe('1.5 MB')
		expect(formatFileDate(null)).toBe('Not available')
		expect(formatFileDate(Number.NaN)).toBe('Not available')
		expect(formatFileDate(0)).toBe('Jan 1, 1970')
	})

	it('keeps short values and middle-truncates only display text', () => {
		expect(middleEllipsis('editor.exe', 20)).toBe('editor.exe')
		expect(middleEllipsis('1234567890', 7)).toBe('123…890')
	})

	it('builds a stable safe report without execution or registry data', () => {
		const report = buildAppReport(app, details)

		expect(report.indexOf('Application')).toBeLessThan(
			report.indexOf('Installation'),
		)
		expect(report.indexOf('Installation')).toBeLessThan(
			report.indexOf('File details'),
		)
		expect(report).toContain('Example Editor')
		expect(report).toContain('1.5 MB')
		expect(report).not.toContain('registry:private-key')
	})

	it('reports a Windows Start App package identity without a resolved executable path', () => {
		const report = buildAppReport(
			{
				...app,
				path: 'Microsoft.AutoGenerated.{TaskScheduler}',
				launchKind: 'app_user_model_id',
				sourceKind: 'start_apps',
			},
			details,
		)

		expect(report).toContain(
			'Launch target: Microsoft.AutoGenerated.{TaskScheduler}',
		)
	})
})
