use crate::catalog::{AppInfo, LaunchKind, SourceKind};
use std::path::Path;

const DOCUMENT_EXTENSIONS: &[&str] = &[
    "url", "chm", "pdf", "htm", "html", "md", "txt", "rtf", "hlp", "mht", "xps",
];

pub(super) fn is_documentation_shortcut(app: &AppInfo) -> bool {
    if app.source_kind == SourceKind::StartApps
        && app.launch_kind == LaunchKind::AppUserModelId
        && (opens_a_document_target(&app.path)
            || app
                .resolved_path
                .as_deref()
                .is_some_and(opens_a_document_target))
    {
        return true;
    }
    if !is_registered_shortcut_surface(app) {
        return false;
    }
    if app
        .resolved_path
        .as_deref()
        .is_some_and(opens_a_document_target)
    {
        return true;
    }
    if app.name.trim().eq_ignore_ascii_case("samples")
        && is_sdk_samples_path(&app.path)
        && app
            .resolved_path
            .as_deref()
            .is_some_and(is_sdk_samples_path)
    {
        return true;
    }
    has_documentation_name(&app.name)
}

fn is_registered_shortcut_surface(app: &AppInfo) -> bool {
    match app.source_kind {
        SourceKind::StartMenu => app.launch_kind == LaunchKind::Shortcut,
        SourceKind::StartApps => {
            app.launch_kind == LaunchKind::AppUserModelId
                && app
                    .path
                    .to_lowercase()
                    .starts_with("microsoft.autogenerated.")
        }
        _ => false,
    }
}

fn opens_a_document_target(target: &str) -> bool {
    if is_absolute_http_url(target) {
        return true;
    }
    Path::new(target.trim().trim_matches('"'))
        .extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| {
            DOCUMENT_EXTENSIONS
                .iter()
                .any(|known| extension.eq_ignore_ascii_case(known))
        })
}

fn has_documentation_name(name: &str) -> bool {
    let normalized = name.to_lowercase();
    if normalized.contains("release notes") || normalized.contains("what's new") {
        return true;
    }
    normalized
        .split(|character: char| !character.is_alphanumeric())
        .filter(|token| !token.is_empty())
        .any(|token| {
            matches!(
                token,
                "documentation"
                    | "docs"
                    | "manual"
                    | "website"
                    | "reference"
                    | "help"
                    | "документация"
                    | "сайт"
                    | "справка"
                    | "руководство"
            )
        })
}

fn is_absolute_http_url(value: &str) -> bool {
    let normalized = value.trim().to_ascii_lowercase();
    let Some(remainder) = normalized
        .strip_prefix("https://")
        .or_else(|| normalized.strip_prefix("http://"))
    else {
        return false;
    };
    let authority = remainder.split(['/', '?', '#']).next().unwrap_or_default();
    !authority.is_empty() && !authority.chars().any(char::is_whitespace)
}

fn is_sdk_samples_path(path: &str) -> bool {
    let components = path
        .replace('/', r"\")
        .split(r"\")
        .filter(|component| !component.is_empty())
        .map(|component| {
            Path::new(component)
                .file_stem()
                .and_then(|value| value.to_str())
                .unwrap_or(component)
                .to_lowercase()
        })
        .collect::<Vec<_>>();
    components
        .windows(2)
        .any(|pair| pair[0] == "sdk" && pair[1] == "samples")
}

#[cfg(test)]
mod tests {
    use super::super::testing::{candidate, start_menu_shortcut};
    use super::super::ArtifactKind;
    use crate::catalog::machine::MachineFacts;
    use crate::catalog::{AppInfo, LaunchKind, SourceKind};

    fn classify(app: &AppInfo, internal_name: Option<&str>) -> ArtifactKind {
        super::super::classify(app, internal_name, &MachineFacts::empty())
    }

    #[test]
    fn start_menu_documentation_shortcuts_are_separated() {
        for name in [
            "Node.js website",
            "AIDA64 Extreme website",
            "Документация AIDA64 Extreme",
            "Сайт AIDA64 Extreme в Интернете",
            "Application Verifier Help",
            "MSI Afterburner skin format reference",
            "RivaTuner Statistics Server localization reference",
        ] {
            let mut app = candidate(name, &format!(r"C:\Start Menu\{name}.lnk"));
            app.source_kind = SourceKind::StartMenu;
            app.launch_kind = LaunchKind::Shortcut;
            assert_eq!(classify(&app, None), ArtifactKind::Documentation, "{name}");
        }

        let mut app = candidate("Microsoft Edge", r"C:\Start Menu\Microsoft Edge.lnk");
        app.source_kind = SourceKind::StartMenu;
        app.launch_kind = LaunchKind::Shortcut;
        assert_eq!(classify(&app, None), ArtifactKind::Application);
    }

    #[test]
    fn a_file_url_to_a_document_is_documentation_like_its_start_menu_twin() {
        let mut app = candidate(
            "PostgreSQL documentation",
            r"file://C:\Program Files\PostgreSQL\15/doc/postgresql/html/index.html",
        );
        app.source_kind = SourceKind::StartApps;
        app.launch_kind = LaunchKind::AppUserModelId;
        app.resolved_path = Some(app.path.clone());
        assert_eq!(classify(&app, None), ArtifactKind::Documentation);

        let mut program = candidate("Vendor tool", r"file://C:\Program Files\Vendor\tool.exe");
        program.source_kind = SourceKind::StartApps;
        program.launch_kind = LaunchKind::AppUserModelId;
        program.resolved_path = Some(program.path.clone());
        assert_eq!(classify(&program, None), ArtifactKind::Application);
    }

    #[test]
    fn url_backed_start_apps_are_documentation() {
        let mut url_app_id = candidate("Vendor portal", "https://vendor.example/help");
        url_app_id.source_kind = SourceKind::StartApps;
        url_app_id.launch_kind = LaunchKind::AppUserModelId;
        assert_eq!(classify(&url_app_id, None), ArtifactKind::Documentation);

        let mut url_target = candidate("Vendor portal", "Vendor.Product!Portal");
        url_target.source_kind = SourceKind::StartApps;
        url_target.launch_kind = LaunchKind::AppUserModelId;
        url_target.resolved_path = Some("HTTPS://vendor.example/help".into());
        assert_eq!(classify(&url_target, None), ArtifactKind::Documentation);

        for (path, target) in [
            ("Vendor.Website!App", None),
            (
                "Vendor.Browser!App",
                Some(r"C:\Program Files\Vendor\browser.exe"),
            ),
            ("steam://run/123", None),
        ] {
            let mut ordinary = candidate("Vendor website", path);
            ordinary.source_kind = SourceKind::StartApps;
            ordinary.launch_kind = LaunchKind::AppUserModelId;
            ordinary.resolved_path = target.map(str::to_string);
            assert_eq!(
                classify(&ordinary, None),
                ArtifactKind::Application,
                "{path}"
            );
        }
    }

    #[test]
    fn start_menu_shortcuts_to_windows_sdk_urls_are_documentation() {
        for (name, target) in [
            (
                "Tools for Windows Store Apps",
                r"C:\Program Files (x86)\Windows Kits\10\Shortcuts\WindowsStoreAppDevCenterToolsDocumentation.url",
            ),
            (
                "Samples for Desktop Apps",
                r"C:\Program Files (x86)\Windows Kits\10\Shortcuts\DesktopDevCenterSamples.url",
            ),
        ] {
            let shortcut_path = format!(
                r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Windows Kits\Windows Software Development Kit\{name}.lnk"
            );
            let app = start_menu_shortcut(name, &shortcut_path, target);
            assert_eq!(classify(&app, None), ArtifactKind::Documentation, "{name}");
        }
    }

    #[test]
    fn localized_shortcuts_are_documentation_through_their_target() {
        for (name, target) in [
            ("Hilfe", r"C:\Program Files\Vendor\hilfe.chm"),
            ("Aide utilisateur", r"C:\Program Files\Vendor\guide.pdf"),
            ("ヘルプ", r"C:\Program Files\Vendor\help.htm"),
            ("Podręcznik", r"C:\Program Files\Vendor\podrecznik.rtf"),
            ("Instrukcja", r"C:\Program Files\Vendor\readme.txt"),
        ] {
            let app = start_menu_shortcut(name, &format!(r"C:\Menu\{name}.lnk"), target);
            assert_eq!(classify(&app, None), ArtifactKind::Documentation, "{name}");
        }

        let program = start_menu_shortcut(
            "Rechnungsprogramm",
            r"C:\Menu\Rechnungsprogramm.lnk",
            r"C:\Program Files\Vendor\rechnung.exe",
        );
        assert_eq!(classify(&program, None), ArtifactKind::Application);
    }

    #[test]
    fn an_apps_folder_twin_of_a_documentation_shortcut_is_documentation_too() {
        let mut twin = candidate(
            "Python 3.14 Module Docs (64-bit)",
            "Microsoft.AutoGenerated.{2AD88A19-430D-1BB6-5461-9708F456DF10}",
        );
        twin.source_kind = SourceKind::StartApps;
        twin.launch_kind = LaunchKind::AppUserModelId;
        twin.resolved_path = Some(r"C:\Python314\python.exe".into());
        assert_eq!(classify(&twin, None), ArtifactKind::Documentation);

        let mut manuals = candidate(
            "Python 3.14 Manuals (64-bit)",
            "Microsoft.AutoGenerated.{3BE99B2A-541E-2CC7-6572-A819F567EF21}",
        );
        manuals.source_kind = SourceKind::StartApps;
        manuals.launch_kind = LaunchKind::AppUserModelId;
        manuals.resolved_path = Some(r"C:\Python314\Doc\html\index.html".into());
        assert_eq!(classify(&manuals, None), ArtifactKind::Documentation);

        let mut store_app = candidate("Docs Reader", "Contoso.DocsReader_8wekyb3d8bbwe!App");
        store_app.source_kind = SourceKind::StartApps;
        store_app.launch_kind = LaunchKind::AppUserModelId;
        assert_eq!(classify(&store_app, None), ArtifactKind::Application);
    }

    #[test]
    fn sdk_samples_folder_shortcut_is_documentation_without_matching_generic_samples() {
        let sdk_samples = start_menu_shortcut(
            "Samples",
            r"C:\Users\Example\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MSI Afterburner\SDK\Samples.lnk",
            r"D:\Apps\MSI Afterburner\SDK\Samples",
        );
        assert_eq!(classify(&sdk_samples, None), ArtifactKind::Documentation);

        let ordinary_samples = start_menu_shortcut(
            "Samples",
            r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Photo Editor\Samples.lnk",
            r"D:\Apps\Photo Editor\Samples",
        );
        assert_eq!(classify(&ordinary_samples, None), ArtifactKind::Application);
    }
}
