//! The marker predicates behind `classify_visibility`, split by what kind of evidence they read.
//!
//! `structural` inspects the shape of a record — how Windows registered it, what its shortcut
//! targets, whether it resolves to anything. Those generalize to any machine because they depend
//! on no vocabulary, and they are the only place rejection can come from. `rules` holds the
//! curated needles as data, each bound to the one field where it is evidence and to the strongest
//! outcome its tier of evidence is allowed to produce.

mod rules;
mod structural;

pub(super) use rules::is_corroborated_weak_component;
pub(super) use structural::{
    executable_matches_product, is_architecture_stub_executable, is_command_environment,
    is_dead_autogenerated_startapp, is_framework_package, is_shell_location_shortcut,
    is_steam_prerequisite_depot, is_uninstall_action_name,
};

use super::VisibilityReason;
use crate::catalog::fields::MarkerFields;
use rules::{Outcome, RULES};

/// What the needle tables have to say about a record.
#[derive(Default)]
pub(super) struct TextVerdict {
    /// The first rule strong enough to settle the record into Auxiliary tools, with its score.
    pub(super) forced: Option<(VisibilityReason, i16)>,
    /// Reasons that only add weight, deduplicated, in table order.
    pub(super) weights: Vec<(VisibilityReason, i16)>,
}

pub(super) fn evaluate_text(fields: &MarkerFields) -> TextVerdict {
    let mut verdict = TextVerdict::default();
    for rule in RULES
        .iter()
        .filter(|rule| fields.any(rule.field, rule.needles))
    {
        match rule.effect() {
            Outcome::ForceAuxiliary(score) => {
                if verdict.forced.is_none() {
                    verdict.forced = Some((rule.reason, score));
                }
            }
            // A record can match several component needles at once — a local file name and the
            // toolchain directory holding it. Each match is real evidence and each is counted, but
            // the reason is recorded once so the explanation stays readable.
            Outcome::Weigh(weight) => verdict.weights.push((rule.reason, weight)),
        }
    }
    verdict
}

impl TextVerdict {
    pub(super) fn total_weight(&self) -> i16 {
        self.weights.iter().map(|(_, weight)| weight).sum()
    }

    pub(super) fn distinct_reasons(&self) -> Vec<VisibilityReason> {
        let mut reasons = Vec::new();
        for (reason, _) in &self.weights {
            if !reasons.contains(reason) {
                reasons.push(*reason);
            }
        }
        reasons
    }
}
