mod rules;
mod structural;

pub(super) use rules::is_corroborated_weak_component;
pub(super) use structural::{
    executable_matches_product, is_architecture_stub_executable, is_command_environment,
    is_dead_autogenerated_startapp, is_framework_package, is_shell_location_shortcut,
    is_steam_prerequisite_depot, is_uninstall_action_name,
};

use super::VisibilityReason;
use crate::catalog::fields::MarkerFields;
use rules::{Outcome, RULES};

#[derive(Default)]
pub(super) struct TextVerdict {
    pub(super) forced: Option<(VisibilityReason, i16)>,
    pub(super) weights: Vec<(VisibilityReason, i16)>,
}

pub(super) fn evaluate_text(fields: &MarkerFields) -> TextVerdict {
    let mut verdict = TextVerdict::default();
    for rule in RULES
        .iter()
        .filter(|rule| fields.any(rule.field, rule.needles))
    {
        match rule.effect() {
            Outcome::ForceAuxiliary(score) => {
                if verdict.forced.is_none() {
                    verdict.forced = Some((rule.reason, score));
                }
            }
            Outcome::Weigh(weight) => verdict.weights.push((rule.reason, weight)),
        }
    }
    verdict
}

impl TextVerdict {
    pub(super) fn total_weight(&self) -> i16 {
        self.weights.iter().map(|(_, weight)| weight).sum()
    }

    pub(super) fn distinct_reasons(&self) -> Vec<VisibilityReason> {
        let mut reasons = Vec::new();
        for (reason, _) in &self.weights {
            if !reasons.contains(reason) {
                reasons.push(*reason);
            }
        }
        reasons
    }
}
