use crate::catalog::{AppInfo, LaunchKind, SourceKind};
use std::path::Path;

pub(in crate::catalog::visibility) fn is_dead_autogenerated_startapp(app: &AppInfo) -> bool {
    app.launch_kind == LaunchKind::AppUserModelId
        && app
            .path
            .to_lowercase()
            .starts_with("microsoft.autogenerated.")
        && app
            .resolved_path
            .as_deref()
            .map(str::trim)
            .unwrap_or_default()
            .is_empty()
}

pub(in crate::catalog::visibility) fn is_framework_package(app: &AppInfo) -> bool {
    if app.source_kind != SourceKind::Msix {
        return false;
    }
    let value = format!(
        "{} {}",
        app.name.to_lowercase(),
        app.product_name
            .as_deref()
            .unwrap_or_default()
            .to_lowercase()
    );
    [
        "microsoft.vclibs",
        "microsoft.net.native",
        "microsoft.ui.xaml",
        "microsoft.web.webview2",
        "microsoft.services.store.engagement",
        "directx",
    ]
    .iter()
    .any(|marker| value.contains(marker))
}

pub(in crate::catalog::visibility) fn is_uninstall_action_name(app: &AppInfo) -> bool {
    app.name
        .to_lowercase()
        .split(|character: char| !character.is_alphanumeric())
        .find(|token| !token.is_empty())
        .is_some_and(|first| matches!(first, "uninstall" | "удалить" | "деинсталляция"))
}

pub(in crate::catalog::visibility) fn is_steam_prerequisite_depot(app: &AppInfo) -> bool {
    if app.source_kind != SourceKind::Steam {
        return false;
    }
    let name = app.name.to_lowercase();
    if name.contains("steamworks common redistributables") || name.contains("steamworks shared") {
        return true;
    }
    [
        app.install_location.as_deref(),
        app.resolved_path.as_deref(),
        app.product_name.as_deref(),
    ]
    .into_iter()
    .flatten()
    .any(|value| {
        let normalized = value.replace('/', r"\").to_lowercase();
        normalized.contains(r"\_commonredist\") || normalized.ends_with(r"\steamworks shared")
    })
}

pub(in crate::catalog::visibility) fn executable_matches_product(app: &AppInfo) -> bool {
    let stem = Path::new(&app.path)
        .file_stem()
        .and_then(|value| value.to_str())
        .map(normalized_identity_text)
        .unwrap_or_default();
    if stem.len() < 3 {
        return false;
    }
    [&app.name, app.product_name.as_deref().unwrap_or_default()]
        .iter()
        .map(|value| normalized_identity_text(value))
        .any(|value| value == stem || value.starts_with(&stem))
}

fn normalized_identity_text(value: &str) -> String {
    value
        .chars()
        .filter(|character| character.is_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

pub(in crate::catalog::visibility) fn is_architecture_stub_executable(path: &str) -> bool {
    Path::new(path.trim().trim_matches('"'))
        .file_stem()
        .and_then(|stem| stem.to_str())
        .is_some_and(|stem| stem == "32" || stem == "64")
}

pub(in crate::catalog::visibility) fn is_command_environment(app: &AppInfo) -> bool {
    let name = app.name.to_lowercase();
    const NAME_MARKERS: &[&str] = &[
        "developer command prompt",
        "developer powershell",
        "native tools command prompt",
        "cross tools command prompt",
        "command prompt for vs",
        "command line client",
        "additional tools for node",
        "safe mode",
        "безопасный режим",
    ];
    if NAME_MARKERS.iter().any(|marker| name.contains(marker)) {
        return true;
    }
    if app
        .resolved_path
        .as_deref()
        .is_some_and(is_command_prompt_path)
    {
        return true;
    }
    let has_arguments = app
        .launch_arguments
        .as_deref()
        .is_some_and(|value| !value.trim().is_empty());
    has_arguments
        && app
            .resolved_path
            .as_deref()
            .is_some_and(is_interpreter_host_path)
}

fn is_command_prompt_path(path: &str) -> bool {
    Path::new(path.trim().trim_matches('"'))
        .file_name()
        .and_then(|value| value.to_str())
        .is_some_and(|file| file.eq_ignore_ascii_case("cmd.exe"))
}

fn is_interpreter_host_path(path: &str) -> bool {
    let file = Path::new(path.trim().trim_matches('"'))
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or(path)
        .to_ascii_lowercase();
    matches!(
        file.as_str(),
        "cmd.exe"
            | "powershell.exe"
            | "pwsh.exe"
            | "wscript.exe"
            | "cscript.exe"
            | "mshta.exe"
            | "rundll32.exe"
            | "python.exe"
            | "pythonw.exe"
            | "py.exe"
            | "mysql.exe"
            | "node.exe"
            | "wsl.exe"
    )
}

pub(in crate::catalog::visibility) fn is_shell_location_shortcut(app: &AppInfo) -> bool {
    let targets_explorer = app.resolved_path.as_deref().is_some_and(|path| {
        Path::new(path.trim().trim_matches('"'))
            .file_name()
            .and_then(|value| value.to_str())
            .is_some_and(|file| file.eq_ignore_ascii_case("explorer.exe"))
    });
    let has_arguments = app
        .launch_arguments
        .as_deref()
        .is_some_and(|value| !value.trim().is_empty());
    targets_explorer && has_arguments
}
