//! Markers that read the shape of a record rather than words in it: how Windows registered it,
//! what its shortcut actually targets, whether it resolves to anything at all.
//!
//! These generalize to any machine by construction, because none of them depends on a curated
//! vocabulary. Only this file may look at an AppUserModelId, and only as structure.

use crate::catalog::{AppInfo, LaunchKind, SourceKind};
use std::path::Path;

/// A `Microsoft.AutoGenerated.{GUID}` Start-App with no resolvable launch target is a Start-Menu
/// folder/group that Windows synthesized into a pseudo-app (e.g. the "Windows Software Development
/// Kit" folder). It cannot launch anything, so it belongs in Auxiliary tools rather than the main
/// catalog. Real Store apps use a package-family AUMID, and VS developer prompts — also
/// AutoGenerated — resolve to `cmd.exe`, so neither is affected.
pub(in crate::catalog::visibility) fn is_dead_autogenerated_startapp(app: &AppInfo) -> bool {
    app.launch_kind == LaunchKind::AppUserModelId
        && app
            .path
            .to_lowercase()
            .starts_with("microsoft.autogenerated.")
        && app
            .resolved_path
            .as_deref()
            .map(str::trim)
            .unwrap_or_default()
            .is_empty()
}

/// MSIX/Store framework packages (`Microsoft.VCLibs`, `Microsoft.UI.Xaml`, the WebView2 runtime,
/// DirectX) are shared runtimes shipped alongside real apps, never something a user launches.
/// Scoped to the MSIX source and to full package identifiers, so an ordinary app whose name merely
/// mentions one is unaffected.
pub(in crate::catalog::visibility) fn is_framework_package(app: &AppInfo) -> bool {
    if app.source_kind != SourceKind::Msix {
        return false;
    }
    let value = format!(
        "{} {}",
        app.name.to_lowercase(),
        app.product_name
            .as_deref()
            .unwrap_or_default()
            .to_lowercase()
    );
    [
        "microsoft.vclibs",
        "microsoft.net.native",
        "microsoft.ui.xaml",
        "microsoft.web.webview2",
        "microsoft.services.store.engagement",
        "directx",
    ]
    .iter()
    .any(|marker| value.contains(marker))
}

/// A shortcut whose display name *starts with* an uninstall verb: `Uninstall Git`, `Uninstall`,
/// `Удалить AULA F75`.
///
/// The first token is what makes this safe. Matching the word anywhere removed `Total Uninstall`
/// and `IObit Uninstaller`, real products; requiring a trailing space (`"uninstall "`) fixed that
/// but then missed the bare `Uninstall .lnk` an installer drops with no product name after it, so
/// it sat in All apps. A verb in first position is the shape of a command, not of a product name.
pub(in crate::catalog::visibility) fn is_uninstall_action_name(app: &AppInfo) -> bool {
    app.name
        .to_lowercase()
        .split(|character: char| !character.is_alphanumeric())
        .find(|token| !token.is_empty())
        .is_some_and(|first| matches!(first, "uninstall" | "удалить" | "деинсталляция"))
}

/// Steam's shared prerequisites depot: a library entry that holds the redistributables games
/// install (`steamapps\common\Steamworks Shared\_CommonRedist\...`), not a game.
///
/// Both signals are Valve's own constants, identical on every machine with Steam: the app name
/// Valve publishes for app 228980, and the `_CommonRedist` folder every Steam title ships its
/// prerequisites in. Recognizing the folder also covers a title whose depot is named differently.
pub(in crate::catalog::visibility) fn is_steam_prerequisite_depot(app: &AppInfo) -> bool {
    if app.source_kind != SourceKind::Steam {
        return false;
    }
    let name = app.name.to_lowercase();
    if name.contains("steamworks common redistributables") || name.contains("steamworks shared") {
        return true;
    }
    [
        app.install_location.as_deref(),
        app.resolved_path.as_deref(),
        app.product_name.as_deref(),
    ]
    .into_iter()
    .flatten()
    .any(|value| {
        let normalized = value.replace('/', r"\").to_lowercase();
        normalized.contains(r"\_commonredist\") || normalized.ends_with(r"\steamworks shared")
    })
}

pub(in crate::catalog::visibility) fn executable_matches_product(app: &AppInfo) -> bool {
    let stem = Path::new(&app.path)
        .file_stem()
        .and_then(|value| value.to_str())
        .map(normalized_identity_text)
        .unwrap_or_default();
    if stem.len() < 3 {
        return false;
    }
    [&app.name, app.product_name.as_deref().unwrap_or_default()]
        .iter()
        .map(|value| normalized_identity_text(value))
        .any(|value| value == stem || value.starts_with(&stem))
}

fn normalized_identity_text(value: &str) -> String {
    value
        .chars()
        .filter(|character| character.is_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

/// An executable named only after its architecture (`32.exe`, `64.exe`) is a packaged component or
/// self-extractor stub, not an application a user launches — its card name comes from the parent
/// folder, and its real product metadata belongs to something else.
pub(in crate::catalog::visibility) fn is_architecture_stub_executable(path: &str) -> bool {
    Path::new(path.trim().trim_matches('"'))
        .file_stem()
        .and_then(|stem| stem.to_str())
        .is_some_and(|stem| stem == "32" || stem == "64")
}

/// A command environment opens a configured interpreter shell (a VS developer prompt, a Node.js
/// prompt) rather than an application. A regular user launching software does not pick these; they
/// belong in Auxiliary tools. Plain Command Prompt is Auxiliary too; argument-free Windows
/// PowerShell remains Primary.
pub(in crate::catalog::visibility) fn is_command_environment(app: &AppInfo) -> bool {
    let name = app.name.to_lowercase();
    const NAME_MARKERS: &[&str] = &[
        "developer command prompt",
        "developer powershell",
        "native tools command prompt",
        "cross tools command prompt",
        "command prompt for vs",
        "command line client",
        // A setup/toolchain action ("Install Additional Tools for Node.js") is not an app.
        "additional tools for node",
        // A diagnostic "safe mode" launcher opens the real app in a recovery mode — not the way
        // a user launches it day to day.
        "safe mode",
        "безопасный режим",
    ];
    if NAME_MARKERS.iter().any(|marker| name.contains(marker)) {
        return true;
    }
    if app
        .resolved_path
        .as_deref()
        .is_some_and(is_command_prompt_path)
    {
        return true;
    }
    let has_arguments = app
        .launch_arguments
        .as_deref()
        .is_some_and(|value| !value.trim().is_empty());
    has_arguments
        && app
            .resolved_path
            .as_deref()
            .is_some_and(is_interpreter_host_path)
}

fn is_command_prompt_path(path: &str) -> bool {
    Path::new(path.trim().trim_matches('"'))
        .file_name()
        .and_then(|value| value.to_str())
        .is_some_and(|file| file.eq_ignore_ascii_case("cmd.exe"))
}

fn is_interpreter_host_path(path: &str) -> bool {
    let file = Path::new(path.trim().trim_matches('"'))
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or(path)
        .to_ascii_lowercase();
    matches!(
        file.as_str(),
        "cmd.exe"
            | "powershell.exe"
            | "pwsh.exe"
            | "wscript.exe"
            | "cscript.exe"
            | "mshta.exe"
            | "rundll32.exe"
            | "python.exe"
            | "pythonw.exe"
            | "py.exe"
            | "mysql.exe"
            | "node.exe"
            | "wsl.exe"
    )
}

/// A shortcut that opens a folder in File Explorer (`explorer.exe "C:\some\folder"`) rather than
/// launching a program. It carries a path argument; the real File Explorer resolves to a bare
/// `explorer.exe` with no arguments and must stay a normal app.
pub(in crate::catalog::visibility) fn is_shell_location_shortcut(app: &AppInfo) -> bool {
    let targets_explorer = app.resolved_path.as_deref().is_some_and(|path| {
        Path::new(path.trim().trim_matches('"'))
            .file_name()
            .and_then(|value| value.to_str())
            .is_some_and(|file| file.eq_ignore_ascii_case("explorer.exe"))
    });
    let has_arguments = app
        .launch_arguments
        .as_deref()
        .is_some_and(|value| !value.trim().is_empty());
    targets_explorer && has_arguments
}
