use crate::catalog::sync::scan_control::ScanControl;
use crate::catalog::{
    classify::classify, filters::is_invalid_display_name, stable_id, AppInfo, LaunchKind,
    SourceKind,
};
use crate::platform::windows::apps_folder::{self, StartAppEntry};
use crate::platform::windows::package_registry;
use std::collections::HashMap;

mod package;

pub(in crate::catalog) fn scan(control: &ScanControl) -> Option<Vec<AppInfo>> {
    if control.is_cancelled() {
        return None;
    }
    let entries = apps_folder::start_apps(&|| control.is_cancelled())?;
    Some(build_start_apps(
        entries,
        &package_registry::packaged_executables(),
    ))
}

fn build_start_apps(
    entries: Vec<StartAppEntry>,
    executables: &HashMap<String, String>,
) -> Vec<AppInfo> {
    let facts = crate::catalog::machine::MachineFacts::current();
    entries
        .into_iter()
        .filter_map(|entry| {
            let name = entry.name.trim().to_string();
            let app_id = entry.app_id.trim().to_string();
            let resolved_path = entry
                .target
                .as_deref()
                .map(str::trim)
                .filter(|value| !value.is_empty())
                .map(str::to_string);
            if is_invalid_display_name(&name) || app_id.is_empty() {
                return None;
            }
            let mut app = AppInfo {
                id: stable_id(&app_id),
                category: classify(&name, &app_id),
                name,
                path: app_id,
                icon_base64: None,
                artifact_kind: Default::default(),
                launch_kind: LaunchKind::AppUserModelId,
                source_kind: SourceKind::StartApps,
                description: None,
                version: None,
                publisher: None,
                product_name: None,
                original_filename: None,
                install_location: None,
                can_uninstall: false,
                uninstall: None,
                resolved_path,
                shortcut_icon_path: None,
                launch_arguments: None,
                canonical_identity: None,
                preference_identity: None,
                visibility_class: Default::default(),
                visibility_score: 0,
                visibility_reasons: Vec::new(),
                target_availability: None,
                category_reasons: Vec::new(),
                close_risk: None,
            };
            if let Some(identity) = entry.package.as_ref() {
                package::apply(&mut app, identity, executables);
            }
            app.artifact_kind = crate::catalog::artifact::classify(&app, None, &facts);
            if app.artifact_kind != crate::catalog::ArtifactKind::Application {
                app.category = crate::catalog::AppCategory::InstallersDocs;
            }
            Some(app)
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::platform::windows::apps_folder::PackageIdentity;

    fn entry(name: &str, app_id: &str) -> StartAppEntry {
        StartAppEntry {
            name: name.into(),
            app_id: app_id.into(),
            target: None,
            package: None,
        }
    }

    fn targeted(name: &str, app_id: &str, target: &str) -> StartAppEntry {
        StartAppEntry {
            target: Some(target.into()),
            ..entry(name, app_id)
        }
    }

    fn packaged(name: &str, app_id: &str) -> StartAppEntry {
        StartAppEntry {
            package: Some(PackageIdentity {
                full_name: "OpenAI.Codex_26.727.4816.0_x64__2p2nqsd0c76g0".into(),
                install_location: Some(
                    r"C:\Program Files\WindowsApps\OpenAI.Codex_26.727.4816.0_x64__2p2nqsd0c76g0"
                        .into(),
                ),
            }),
            ..entry(name, app_id)
        }
    }

    fn no_executables() -> HashMap<String, String> {
        HashMap::new()
    }

    #[test]
    fn ignores_resource_and_replacement_character_names() {
        let apps = build_start_apps(
            vec![
                entry("ms-resource:AppName", "Package!App"),
                entry("Broken\u{fffd}Name", "Broken!App"),
            ],
            &no_executables(),
        );

        assert!(apps.is_empty());
    }

    #[test]
    fn maps_an_apps_folder_entry_onto_a_catalog_record() {
        let apps = build_start_apps(
            vec![entry("Codex", "OpenAI.Codex_abc!App")],
            &no_executables(),
        );

        assert_eq!(apps[0].name, "Codex");
        assert_eq!(apps[0].path, "OpenAI.Codex_abc!App");
        assert_eq!(apps[0].launch_kind, LaunchKind::AppUserModelId);
    }

    #[test]
    fn preserves_generic_host_targets_as_launch_evidence() {
        let apps = build_start_apps(
            vec![
                targeted(
                    "Ubuntu",
                    "Microsoft.AutoGenerated.{WSL}",
                    r"C:\Program Files\WSL\wsl.exe",
                ),
                targeted(
                    "Командная строка",
                    r"X\cmd.exe",
                    r"C:\Windows\system32\cmd.exe",
                ),
                targeted(
                    "Reload Configuration",
                    "Microsoft.AutoGenerated.{F5}",
                    r"C:\Program Files\PostgreSQL\15\bin\pg_ctl.exe",
                ),
            ],
            &no_executables(),
        );

        let ubuntu = apps.iter().find(|app| app.name == "Ubuntu").unwrap();
        assert_eq!(
            ubuntu.resolved_path.as_deref(),
            Some(r"C:\Program Files\WSL\wsl.exe")
        );
        let cmd = apps.iter().find(|a| a.name == "Командная строка").unwrap();
        assert_eq!(
            cmd.resolved_path.as_deref(),
            Some(r"C:\Windows\system32\cmd.exe")
        );
        let reload = apps
            .iter()
            .find(|a| a.name == "Reload Configuration")
            .unwrap();
        assert!(reload.resolved_path.is_some(), "dedicated tool target kept");
    }

    #[test]
    fn resolves_start_app_target_into_resolved_path() {
        let apps = build_start_apps(
            vec![targeted(
                "Просмотр событий",
                "Microsoft.AutoGenerated.{BB044BFD}",
                r"C:\Windows\system32\eventvwr.msc",
            )],
            &no_executables(),
        );

        assert_eq!(apps.len(), 1);
        assert_eq!(apps[0].name, "Просмотр событий");
        assert_eq!(
            apps[0].resolved_path.as_deref(),
            Some(r"C:\Windows\system32\eventvwr.msc")
        );
    }

    #[test]
    fn trusted_mysql_installer_target_is_classified_without_parsing_the_aumid() {
        let apps = build_start_apps(
            vec![targeted(
                "MySQL Installer - Community",
                "Microsoft.AutoGenerated.{2C7C9013-A7FD-5C12-D811-939AFE2A3592}",
                r"C:\Program Files (x86)\MySQL\MySQL Installer for Windows\MySQLInstaller.exe",
            )],
            &no_executables(),
        );

        assert_eq!(
            apps[0].artifact_kind,
            crate::catalog::ArtifactKind::Installer
        );
        assert_eq!(
            apps[0].category,
            crate::catalog::AppCategory::InstallersDocs
        );
    }

    #[test]
    fn parses_url_backed_start_apps_as_documentation() {
        let apps = build_start_apps(
            vec![targeted(
                "Node.js website",
                "https://nodejs.org/",
                "https://nodejs.org/",
            )],
            &no_executables(),
        );

        assert_eq!(apps.len(), 1);
        assert_eq!(
            apps[0].artifact_kind,
            crate::catalog::ArtifactKind::Documentation
        );
        assert_eq!(
            apps[0].category,
            crate::catalog::AppCategory::InstallersDocs
        );
    }

    #[test]
    fn keeps_start_apps_with_product_words_in_names_or_aumids() {
        let apps = build_start_apps(
            vec![
                entry(
                    "Visual Studio Installer",
                    "Microsoft.VisualStudio.Installer",
                ),
                entry("Uninstall Node.js", "Microsoft.AutoGenerated.Uninstall"),
                entry("Visual Studio Code", "Microsoft.VisualStudioCode"),
            ],
            &no_executables(),
        );

        assert_eq!(
            apps.iter().map(|app| app.name.as_str()).collect::<Vec<_>>(),
            vec![
                "Visual Studio Installer",
                "Uninstall Node.js",
                "Visual Studio Code"
            ]
        );
    }

    #[test]
    fn a_packaged_entry_becomes_an_uninstallable_msix_record() {
        let apps = build_start_apps(
            vec![packaged("Codex", "OpenAI.Codex_2p2nqsd0c76g0!App")],
            &no_executables(),
        );

        assert_eq!(apps[0].source_kind, SourceKind::Msix);
        assert_eq!(apps[0].publisher.as_deref(), Some("OpenAI"));
        assert_eq!(apps[0].version.as_deref(), Some("26.727.4816.0"));
        assert_eq!(apps[0].product_name.as_deref(), Some("OpenAI.Codex"));
        assert!(apps[0].can_uninstall);
        assert_eq!(
            apps[0].uninstall,
            Some(crate::catalog::UninstallTarget::Msix {
                package_full_name: "OpenAI.Codex_26.727.4816.0_x64__2p2nqsd0c76g0".into()
            })
        );
        assert_eq!(apps[0].resolved_path, None);
    }

    #[test]
    fn a_packaged_entry_resolves_its_executable_from_the_package_repository() {
        let executables = HashMap::from([(
            "openai.codex_2p2nqsd0c76g0!app".to_string(),
            r"app\ChatGPT.exe".to_string(),
        )]);

        let apps = build_start_apps(
            vec![packaged("Codex", "OpenAI.Codex_2p2nqsd0c76g0!App")],
            &executables,
        );

        assert_eq!(
            apps[0].resolved_path.as_deref(),
            Some(
                r"C:\Program Files\WindowsApps\OpenAI.Codex_26.727.4816.0_x64__2p2nqsd0c76g0\app\ChatGPT.exe"
            )
        );
    }

    #[test]
    fn a_packaged_entry_ignores_an_executable_registered_for_another_application() {
        let executables = HashMap::from([(
            "other.package_abc!app".to_string(),
            r"app\ChatGPT.exe".to_string(),
        )]);

        let apps = build_start_apps(
            vec![packaged("Codex", "OpenAI.Codex_2p2nqsd0c76g0!App")],
            &executables,
        );

        assert_eq!(apps[0].resolved_path, None);
    }
}
