use crate::catalog::{AppCategory, AppInfo, LaunchKind, SourceKind};

pub(in crate::catalog) struct Rng(pub(in crate::catalog) u64);

impl Rng {
    pub(in crate::catalog) fn next_value(&mut self) -> u64 {
        let mut value = self.0;
        value ^= value << 13;
        value ^= value >> 7;
        value ^= value << 17;
        self.0 = value;
        value
    }

    pub(in crate::catalog) fn pick(&mut self, limit: usize) -> usize {
        (self.next_value() % limit as u64) as usize
    }
}

fn blank(name: &str, path: &str) -> AppInfo {
    AppInfo {
        id: String::new(),
        name: name.into(),
        path: path.into(),
        icon_base64: None,
        artifact_kind: Default::default(),
        category: AppCategory::Other,
        launch_kind: LaunchKind::Executable,
        source_kind: SourceKind::Registry,
        description: None,
        version: None,
        publisher: None,
        product_name: None,
        original_filename: None,
        install_location: None,
        can_uninstall: false,
        uninstall: None,
        resolved_path: None,
        shortcut_icon_path: None,
        launch_arguments: None,
        canonical_identity: None,
        preference_identity: None,
        visibility_class: Default::default(),
        visibility_score: 0,
        visibility_reasons: Vec::new(),
        target_availability: None,
        category_reasons: Vec::new(),
        close_risk: None,
    }
}

pub(super) fn generated_records(seed: u64, count: usize) -> Vec<AppInfo> {
    let mut rng = Rng(seed | 1);
    let mut catalog = Vec::with_capacity(count);
    for index in 0..count {
        let family = rng.pick(count / 3 + 1);
        let vendor = rng.pick(8);
        let root = format!(r"C:\Vendor{vendor}\Product{family}");
        let executable = format!(r"{root}\product{family}.exe");
        let mut entry = blank(&format!("Product {family}"), &executable);
        entry.install_location = Some(root.clone());
        entry.publisher = (rng.pick(4) != 0).then(|| format!("Vendor {vendor}"));
        entry.version = (rng.pick(3) != 0).then(|| format!("1.{}.0", rng.pick(5)));
        match rng.pick(9) {
            0 => {
                entry.source_kind = SourceKind::Registry;
                entry.can_uninstall = true;
            }
            1 => {
                entry.source_kind = SourceKind::StartMenu;
                entry.launch_kind = LaunchKind::Shortcut;
                entry.path = format!(r"C:\Menu\Product{family}-{index}.lnk");
                entry.resolved_path = Some(executable);
            }
            2 => {
                entry.source_kind = SourceKind::Msix;
                entry.launch_kind = LaunchKind::AppUserModelId;
                entry.path = format!("Vendor{vendor}.Product{family}_8wekyb!App");
            }
            3 => {
                entry.source_kind = SourceKind::Steam;
                entry.path = format!("steam://rungameid/{}", 1000 + family);
            }
            4 => {
                entry.source_kind = SourceKind::Portable;
                entry.path = format!(r"{root}\bin\product{family}-helper.exe");
            }
            5 => {
                entry.source_kind = SourceKind::StartMenu;
                entry.launch_kind = LaunchKind::Shortcut;
                entry.name = format!("Product {family} Manual");
                entry.path = format!(r"C:\Menu\Product{family} Manual-{index}.lnk");
                entry.resolved_path = Some(format!(r"{root}\manual.chm"));
            }
            6 => {
                entry.source_kind = SourceKind::Portable;
                entry.name = format!("Product {family}");
                entry.path = format!(r"{root}\Update.exe");
            }
            7 => {
                entry.source_kind = SourceKind::StartMenu;
                entry.launch_kind = LaunchKind::Shortcut;
                entry.name = format!("Product {family} command prompt");
                entry.path = format!(r"C:\Menu\Product{family} prompt-{index}.lnk");
                entry.resolved_path = Some(r"C:\Windows\System32\cmd.exe".into());
                entry.launch_arguments = Some(format!(r#"/k "{root}\env.bat""#));
            }
            _ => {
                entry.source_kind = SourceKind::StartApps;
                entry.launch_kind = LaunchKind::AppUserModelId;
                entry.path = format!("Microsoft.AutoGenerated.{{{family}-{index}}}");
                entry.resolved_path = Some(executable);
            }
        }
        catalog.push(entry);
    }
    catalog
}

pub(super) fn shuffled(records: &[AppInfo], seed: u64) -> Vec<AppInfo> {
    let mut rng = Rng(seed | 1);
    let mut shuffled = records.to_vec();
    for index in (1..shuffled.len()).rev() {
        shuffled.swap(index, rng.pick(index + 1));
    }
    shuffled
}
