//! Text/path marker predicates used by `classify_visibility`. Each answers one narrow "is this a
//! …" question about an app's name, path, and metadata; keeping them here leaves the parent module
//! to the scoring flow.

use crate::catalog::{AppInfo, LaunchKind, SourceKind};
use std::path::Path;

/// A `Microsoft.AutoGenerated.{GUID}` Start-App with no resolvable launch target is a Start-Menu
/// folder/group that Windows synthesized into a pseudo-app (e.g. the "Windows Software Development
/// Kit" folder). It cannot launch anything, so it belongs in Auxiliary tools rather than the main
/// catalog. Real Store apps use a package-family AUMID, and VS developer prompts — also
/// AutoGenerated — resolve to `cmd.exe`, so neither is affected.
pub(super) fn is_dead_autogenerated_startapp(app: &AppInfo) -> bool {
    app.launch_kind == LaunchKind::AppUserModelId
        && app
            .path
            .to_lowercase()
            .starts_with("microsoft.autogenerated.")
        && app
            .resolved_path
            .as_deref()
            .map(str::trim)
            .unwrap_or_default()
            .is_empty()
}

/// MSIX/Store framework packages (`Microsoft.VCLibs`, `Microsoft.UI.Xaml`, the WebView2 runtime,
/// DirectX) are shared runtimes shipped alongside real apps, never something a user launches.
/// Scoped to the MSIX source so an ordinary app whose name merely mentions one is unaffected.
pub(super) fn is_framework_package(app: &AppInfo) -> bool {
    if app.source_kind != SourceKind::Msix {
        return false;
    }
    let value = format!(
        "{} {}",
        app.name.to_lowercase(),
        app.product_name
            .as_deref()
            .unwrap_or_default()
            .to_lowercase()
    );
    contains_any(
        &value,
        &[
            "microsoft.vclibs",
            "microsoft.net.native",
            "microsoft.ui.xaml",
            "microsoft.web.webview2",
            "microsoft.services.store.engagement",
            "directx",
        ],
    )
}

pub(super) fn executable_matches_product(app: &AppInfo) -> bool {
    let stem = Path::new(&app.path)
        .file_stem()
        .and_then(|value| value.to_str())
        .map(normalized_identity_text)
        .unwrap_or_default();
    if stem.len() < 3 {
        return false;
    }
    [&app.name, app.product_name.as_deref().unwrap_or_default()]
        .iter()
        .map(|value| normalized_identity_text(value))
        .any(|value| value == stem || value.starts_with(&stem))
}

fn normalized_identity_text(value: &str) -> String {
    value
        .chars()
        .filter(|character| character.is_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

/// An executable named only after its architecture (`32.exe`, `64.exe`) is a packaged component or
/// self-extractor stub, not an application a user launches — its card name comes from the parent
/// folder, and its real product metadata belongs to something else (e.g. a Yandex binary dropped in
/// a "Крипто про" folder). Treat it as a product component so it lands in Auxiliary tools.
pub(super) fn is_architecture_stub_executable(path: &str) -> bool {
    Path::new(path.trim().trim_matches('"'))
        .file_stem()
        .and_then(|stem| stem.to_str())
        .is_some_and(|stem| stem == "32" || stem == "64")
}

/// SDK sample/demo executables shipped inside a product's developer kit (an `\SDK\Samples\` tree, or
/// a name/description that says so). They are reference code, not an app a user launches, so they
/// belong in Auxiliary tools. Matched over the combined name/path/metadata blob; `\sdk\samples\` is
/// the decisive, unambiguous signal and the phrases catch samples that carry no such path.
pub(super) fn is_sdk_sample(value: &str) -> bool {
    contains_any(
        value,
        &[
            r"\sdk\samples\",
            r"\samples\sharedmemory\",
            "shared memory sample",
            "sample application",
        ],
    )
}

pub(super) fn is_bundled_toolchain_path(path: &str) -> bool {
    contains_any(
        path,
        &[
            r"\.vscode\extensions\",
            r"\.codeium\",
            r"\git\usr\bin\",
            r"\git\mingw32\",
            r"\git\mingw64\",
            r"\codex-runtimes\",
            r"\sdk\samples\",
        ],
    )
}

/// A command environment opens a configured interpreter shell (a VS developer prompt, a
/// Node.js prompt) rather than an application. A regular user launching software does not pick
/// these; they belong in Auxiliary tools. Plain Command Prompt is Auxiliary too; argument-free
/// Windows PowerShell remains Primary.
pub(super) fn is_command_environment(app: &AppInfo) -> bool {
    let name = app.name.to_lowercase();
    const NAME_MARKERS: &[&str] = &[
        "developer command prompt",
        "developer powershell",
        "native tools command prompt",
        "cross tools command prompt",
        "command prompt for vs",
        "command line client",
        // A setup/toolchain action ("Install Additional Tools for Node.js") is not an app.
        "additional tools for node",
        // A diagnostic "safe mode" launcher opens the real app in a recovery mode — not the way
        // a user launches it day to day.
        "safe mode",
        "безопасный режим",
    ];
    if NAME_MARKERS.iter().any(|marker| name.contains(marker)) {
        return true;
    }
    if app
        .resolved_path
        .as_deref()
        .is_some_and(is_command_prompt_path)
    {
        return true;
    }
    let has_arguments = app
        .launch_arguments
        .as_deref()
        .is_some_and(|value| !value.trim().is_empty());
    has_arguments
        && app
            .resolved_path
            .as_deref()
            .is_some_and(is_interpreter_host_path)
}

fn is_command_prompt_path(path: &str) -> bool {
    Path::new(path.trim().trim_matches('"'))
        .file_name()
        .and_then(|value| value.to_str())
        .is_some_and(|file| file.eq_ignore_ascii_case("cmd.exe"))
}

fn is_interpreter_host_path(path: &str) -> bool {
    let file = Path::new(path.trim().trim_matches('"'))
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or(path)
        .to_ascii_lowercase();
    matches!(
        file.as_str(),
        "cmd.exe"
            | "powershell.exe"
            | "pwsh.exe"
            | "wscript.exe"
            | "cscript.exe"
            | "mshta.exe"
            | "rundll32.exe"
            | "python.exe"
            | "pythonw.exe"
            | "py.exe"
            | "mysql.exe"
            | "node.exe"
            | "wsl.exe"
    )
}

/// A shortcut that opens a folder in File Explorer (`explorer.exe "C:\some\folder"`) rather than
/// launching a program — for example the "Windows Software Development Kit" Start-Menu entry, which
/// just opens the Windows Kits folder. It carries a path argument; the real File Explorer resolves
/// to a bare `explorer.exe` with no arguments and must stay a normal app.
pub(super) fn is_shell_location_shortcut(app: &AppInfo) -> bool {
    let targets_explorer = app.resolved_path.as_deref().is_some_and(|path| {
        Path::new(path.trim().trim_matches('"'))
            .file_name()
            .and_then(|value| value.to_str())
            .is_some_and(|file| file.eq_ignore_ascii_case("explorer.exe"))
    });
    let has_arguments = app
        .launch_arguments
        .as_deref()
        .is_some_and(|value| !value.trim().is_empty());
    targets_explorer && has_arguments
}

fn contains_any(value: &str, markers: &[&str]) -> bool {
    markers.iter().any(|marker| value.contains(marker))
}

pub(super) fn is_installer_or_uninstaller(value: &str) -> bool {
    contains_any(
        value,
        &[
            " uninstall",
            "uninstall ",
            "unins000",
            " setup",
            "setup.exe",
            "installer",
            "tsetup",
            "vcredist",
            "vc_redist",
            "redist",
            "bootstrapper",
            // Runtime redistributables masquerading as apps. "webview2 runtime" is precise so a
            // real app named "WebView2 Sample" is not swept up; the MSIX WebView2 framework package
            // is handled separately by `is_framework_package`.
            "webview2 runtime",
            "dxsetup",
            "ndp48",
            // Self-extracting installer stubs (e.g. "Adobe Self Extractor" = AdbeRdr…exe bundled
            // inside another product's \support\ folder).
            "self extractor",
            "self-extractor",
            "adberdr",
        ],
    )
}

pub(super) fn is_documentation(value: &str) -> bool {
    contains_any(
        value,
        &[
            " faq",
            "faqs",
            "documentation",
            "installation notes",
            "release notes",
            "readme",
            "manual",
            "документация",
            "справка",
            "руководство",
        ],
    )
}

pub(super) fn is_maintenance_executable(value: &str) -> bool {
    contains_any(
        value,
        &[
            "update-service",
            "update_service",
            " updater",
            "update.exe",
            "autoupdate",
            "crashhandler",
            "crash handler",
            "crashpad",
            "uninstall.exe",
            "elevation service",
            "elevationservice",
            "werfault",
            "bug report",
            "bugsplat",
            "telemetry",
            "watchdog",
            "squirrel",
            "background task host",
            "backgroundtaskhost",
            // OpenConsole is the PTY/console host bundled by Terminal and Electron applications,
            // not the user-facing Windows Terminal launcher.
            "openconsole.exe",
            // "Reset preferences and cache files"-style shortcuts run the app in a wipe mode
            // instead of opening it; they belong with maintenance, not the player itself.
            "reset preferences",
            "reset cache",
            "reset config",
            "reset settings",
            "сброс настроек",
            "сброс кэш",
        ],
    )
}

pub(super) fn has_runtime_path(path: &str) -> bool {
    contains_any(
        path,
        &[
            r"\bin\",
            r"\lib\",
            r"\runtime\",
            r"\jre\",
            r"\sdk\",
            r"\plugins\",
            r"\resources\",
            r"\resources\app\",
            r"\node_modules\",
            r"\squirrel\",
            r"\packages\",
            r"\dotnet\",
        ],
    )
}

pub(super) fn is_product_component(value: &str) -> bool {
    contains_any(
        value,
        &[
            "iconv.exe",
            "intelliphp.ls",
            "language server",
            "openjdk platform binary",
            // Oracle Java runtime entries ("Java(TM) Platform SE", "Java(TM) SE") are the JRE, a
            // runtime component, not an application a user launches.
            "java(tm)",
            "the curl executable",
            "openssl command",
            "credential manager",
            "gettext",
            "git-lfs",
            "git large file storage",
            "sandbox",
            "compiler",
            " helper",
            "_helper",
            "-helper",
            "web helper",
            "crashpad_handler",
            "broker.exe",
            "subprocess",
            "pwa_launcher",
            "pwa launcher",
            " service.exe",
            " daemon",
            // A bundled utility executable (`AstUtil.exe`, `*Util.exe`) is a maintenance/config
            // helper of its product, not the application a user launches.
            "util.exe",
        ],
    )
}
