use super::{AppInfo, LaunchKind, SourceKind};
use markers::{
    executable_matches_product, has_runtime_path, is_architecture_stub_executable,
    is_bundled_toolchain_path, is_command_environment, is_dead_autogenerated_startapp,
    is_documentation, is_framework_package, is_installer_or_uninstaller, is_maintenance_executable,
    is_product_component, is_sdk_sample, is_shell_location_shortcut,
};
use serde::{Deserialize, Serialize};

mod markers;
mod report;

pub(crate) use report::write_dev_report;

#[derive(Clone, Copy, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum VisibilityClass {
    #[default]
    Primary,
    Auxiliary,
    Rejected,
}

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum VisibilityReason {
    StartMenuRegistration,
    WindowsAppRegistration,
    SteamRegistration,
    PortableCandidate,
    ProductMetadata,
    RegisteredProduct,
    ExecutableProductMatch,
    RuntimeDirectory,
    ProductComponent,
    DocumentationShortcut,
    Installer,
    MaintenanceExecutable,
    FrameworkPackage,
    ShellLocationShortcut,
    SdkSample,
    CommandEnvironment,
    ConsoleApplication,
    InsufficientLaunchEvidence,
    // An unrecognized reason from a newer cache degrades here instead of failing the whole
    // document, mirroring `AppCategory::Other`. Never produced by classification itself.
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct VisibilityDecision {
    pub class: VisibilityClass,
    pub score: i16,
    pub reasons: Vec<VisibilityReason>,
}

pub(crate) fn classify_visibility(app: &AppInfo) -> VisibilityDecision {
    let name = app.name.to_lowercase();
    let path = app.path.to_lowercase().replace('/', r"\");
    let resolved_path = app
        .resolved_path
        .as_deref()
        .unwrap_or_default()
        .to_lowercase()
        .replace('/', r"\");
    let description = app
        .description
        .as_deref()
        .unwrap_or_default()
        .to_lowercase();
    let product_name = app
        .product_name
        .as_deref()
        .unwrap_or_default()
        .to_lowercase();
    let original_filename = app
        .original_filename
        .as_deref()
        .unwrap_or_default()
        .to_lowercase();
    let value =
        format!("{name} {path} {resolved_path} {original_filename} {product_name} {description}");
    let mut score = 0;
    let mut reasons = Vec::new();

    match app.source_kind {
        SourceKind::Steam => {
            score += 60;
            reasons.push(VisibilityReason::SteamRegistration);
        }
        SourceKind::StartApps | SourceKind::Msix => {
            score += 60;
            reasons.push(VisibilityReason::WindowsAppRegistration);
        }
        SourceKind::StartMenu => {
            score += 45;
            reasons.push(VisibilityReason::StartMenuRegistration);
        }
        SourceKind::Portable => {
            score += 10;
            reasons.push(VisibilityReason::PortableCandidate);
        }
        SourceKind::Registry => {}
    }

    if app.source_kind == SourceKind::Registry && app.can_uninstall {
        score += 35;
        reasons.push(VisibilityReason::RegisteredProduct);
    }

    if is_installer_or_uninstaller(&value) {
        return VisibilityDecision {
            class: VisibilityClass::Rejected,
            score: -100,
            reasons: vec![VisibilityReason::Installer],
        };
    }
    if is_documentation(&value) {
        return VisibilityDecision {
            class: VisibilityClass::Rejected,
            score: -80,
            reasons: vec![VisibilityReason::DocumentationShortcut],
        };
    }
    if is_maintenance_executable(&value) {
        return VisibilityDecision {
            class: VisibilityClass::Rejected,
            score: -70,
            reasons: vec![VisibilityReason::MaintenanceExecutable],
        };
    }
    if is_framework_package(app) {
        return VisibilityDecision {
            class: VisibilityClass::Rejected,
            score: -90,
            reasons: vec![VisibilityReason::FrameworkPackage],
        };
    }
    if is_shell_location_shortcut(app) {
        return VisibilityDecision {
            class: VisibilityClass::Rejected,
            score: -60,
            reasons: vec![VisibilityReason::ShellLocationShortcut],
        };
    }

    if app
        .publisher
        .as_deref()
        .is_some_and(|value| !value.trim().is_empty())
        && app
            .description
            .as_deref()
            .is_some_and(|value| !value.trim().is_empty())
    {
        score += 25;
        reasons.push(VisibilityReason::ProductMetadata);
    }

    if executable_matches_product(app) {
        score += 15;
        reasons.push(VisibilityReason::ExecutableProductMatch);
    }

    if has_runtime_path(&path) || has_runtime_path(&resolved_path) {
        score -= 20;
        reasons.push(VisibilityReason::RuntimeDirectory);
    }
    if is_product_component(&value)
        || is_bundled_toolchain_path(&path)
        || is_architecture_stub_executable(&path)
        || is_architecture_stub_executable(&resolved_path)
    {
        score -= 20;
        reasons.push(VisibilityReason::ProductComponent);
    }
    if is_sdk_sample(&value) {
        score -= 20;
        reasons.push(VisibilityReason::SdkSample);
    }
    // A portable executable with no version, publisher, or product name carries no evidence it is a
    // user-facing application; nudge it toward Auxiliary. Combined with a runtime path this settles
    // the entry, while a genuine portable app usually still clears the bar on other signals.
    if app.source_kind == SourceKind::Portable
        && app.version.is_none()
        && app.publisher.is_none()
        && app.product_name.is_none()
    {
        score -= 10;
    }
    if is_command_environment(app) {
        reasons.push(VisibilityReason::CommandEnvironment);
    }

    // A folder-group Start-App that resolves to nothing cannot launch anything; keep it out of the
    // main catalog even though the AppUserModelId fast-path would otherwise force it Primary.
    if is_dead_autogenerated_startapp(app) {
        reasons.push(VisibilityReason::InsufficientLaunchEvidence);
        return VisibilityDecision {
            class: VisibilityClass::Auxiliary,
            score,
            reasons,
        };
    }

    // A command environment and a product component are auxiliary regardless of score or launch
    // kind — including the AppUserModelId fast-path, which is exactly how the VS developer prompts
    // reach the catalog.
    let class = if reasons.iter().any(|reason| {
        matches!(
            reason,
            VisibilityReason::ProductComponent
                | VisibilityReason::CommandEnvironment
                | VisibilityReason::SdkSample
        )
    }) {
        VisibilityClass::Auxiliary
    } else if score >= 20 || app.launch_kind == LaunchKind::AppUserModelId {
        VisibilityClass::Primary
    } else {
        reasons.push(VisibilityReason::InsufficientLaunchEvidence);
        VisibilityClass::Auxiliary
    };

    VisibilityDecision {
        class,
        score,
        reasons,
    }
}

pub(crate) fn apply_visibility(app: &mut AppInfo) {
    let decision = classify_visibility(app);
    app.visibility_class = decision.class;
    app.visibility_score = decision.score;
    app.visibility_reasons = decision.reasons;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::{AppInfo, LaunchKind, SourceKind};
    use serde::Deserialize;

    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Fixture {
        name: String,
        path: String,
        source: SourceKind,
        expected: String,
        description: Option<String>,
        publisher: Option<String>,
        original_filename: Option<String>,
        resolved_path: Option<String>,
        can_uninstall: Option<bool>,
    }

    fn candidate(name: &str, path: &str, source_kind: SourceKind) -> AppInfo {
        AppInfo {
            id: name.into(),
            name: name.into(),
            path: path.into(),
            icon_base64: None,
            category: Default::default(),
            launch_kind: if path.ends_with(".lnk") {
                LaunchKind::Shortcut
            } else {
                LaunchKind::Executable
            },
            source_kind,
            description: None,
            version: None,
            publisher: None,
            product_name: None,
            original_filename: None,
            install_location: None,
            can_uninstall: false,
            uninstall: None,
            resolved_path: None,
            shortcut_icon_path: None,
            launch_arguments: None,
            canonical_identity: None,
            preference_identity: None,
            visibility_class: Default::default(),
            visibility_score: 0,
            visibility_reasons: Vec::new(),
        }
    }

    #[test]
    fn keeps_explicit_user_launchers_primary() {
        let git_bash = candidate(
            "Git Bash",
            r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Git\Git Bash.lnk",
            SourceKind::StartMenu,
        );
        assert_eq!(
            classify_visibility(&git_bash).class,
            VisibilityClass::Primary
        );
    }

    #[test]
    fn shortcut_to_runtime_component_is_auxiliary_despite_start_menu_location() {
        let mut shortcut = candidate(
            "PHP Tools",
            r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PHP Tools.lnk",
            SourceKind::StartMenu,
        );
        shortcut.resolved_path = Some(r"C:\Editor\plugins\intelliphp.ls.exe".into());

        let decision = classify_visibility(&shortcut);

        assert_eq!(decision.class, VisibilityClass::Auxiliary);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::ProductComponent));
    }

    #[test]
    fn classifies_known_product_components_as_auxiliary() {
        for (name, path, description) in [
            ("iconv", r"C:\Git\usr\bin\iconv.exe", None),
            (
                "intelliphp.ls",
                r"C:\Editor\plugins\intelliphp.ls.exe",
                Some("PHP language server"),
            ),
            (
                "OpenJDK Platform binary",
                r"C:\Java\runtime\bin\javaw.exe",
                Some("OpenJDK Platform binary"),
            ),
            (
                "The curl executable",
                r"C:\Git\mingw64\bin\curl.exe",
                Some("The curl executable"),
            ),
        ] {
            let mut app = candidate(name, path, SourceKind::Portable);
            app.description = description.map(str::to_string);
            assert_eq!(
                classify_visibility(&app).class,
                VisibilityClass::Auxiliary,
                "{name}"
            );
        }
    }

    #[test]
    fn rejects_installers_uninstallers_and_maintenance_shortcuts() {
        for (name, path) in [
            ("Telegram Desktop Setup", r"C:\Downloads\tsetup.exe"),
            ("Uninstall Git", r"C:\Git\Uninstall Git.lnk"),
            ("Git FAQs", r"C:\Git\Git FAQs.lnk"),
            ("Example Update Service", r"C:\Example\update-service.exe"),
        ] {
            let app = candidate(name, path, SourceKind::Portable);
            assert_eq!(
                classify_visibility(&app).class,
                VisibilityClass::Rejected,
                "{name}"
            );
        }
    }

    #[test]
    fn keeps_unknown_apps_conservative_instead_of_rejecting_them() {
        let app = candidate(
            "Example Studio",
            r"D:\Apps\Example Studio\ExampleStudio.exe",
            SourceKind::Portable,
        );
        assert_ne!(classify_visibility(&app).class, VisibilityClass::Rejected);
        assert!(!classify_visibility(&app).reasons.is_empty());
    }

    #[test]
    fn promotes_unknown_portable_apps_with_coherent_product_metadata() {
        let mut app = candidate(
            "Example Studio",
            r"D:\Apps\Example Studio\ExampleStudio.exe",
            SourceKind::Portable,
        );
        app.publisher = Some("Example Software".into());
        app.description = Some("Example Studio desktop application".into());

        let decision = classify_visibility(&app);

        assert_eq!(decision.class, VisibilityClass::Primary);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::ProductMetadata));
    }

    #[test]
    fn keeps_registered_products_with_an_uninstaller_primary() {
        let mut app = candidate(
            "Example Editor",
            r"C:\Program Files\Example\Editor.exe",
            SourceKind::Registry,
        );
        app.can_uninstall = true;

        let decision = classify_visibility(&app);

        assert_eq!(decision.class, VisibilityClass::Primary);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::RegisteredProduct));
    }

    #[test]
    fn original_filename_exposes_a_renamed_helper() {
        let mut app = candidate(
            "Workspace Agent",
            r"D:\Apps\Workspace\random-name.exe",
            SourceKind::Portable,
        );
        app.original_filename = Some("notification_helper.exe".into());
        app.product_name = Some("Workspace".into());

        let decision = classify_visibility(&app);

        assert_eq!(decision.class, VisibilityClass::Auxiliary);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::ProductComponent));
    }

    #[test]
    fn neutral_original_filename_does_not_override_registered_product_evidence() {
        let mut app = candidate(
            "Example Editor",
            r"C:\Program Files\Example\Editor.exe",
            SourceKind::Registry,
        );
        app.can_uninstall = true;
        app.original_filename = Some("editor.exe".into());
        app.product_name = Some("Example Editor".into());

        assert_eq!(classify_visibility(&app).class, VisibilityClass::Primary);
    }

    #[test]
    fn original_filename_exposes_a_renamed_installer() {
        let mut app = candidate(
            "Workspace Download",
            r"D:\Apps\Workspace\payload.exe",
            SourceKind::Portable,
        );
        app.original_filename = Some("product-setup.exe".into());

        let decision = classify_visibility(&app);

        assert_eq!(decision.class, VisibilityClass::Rejected);
        assert_eq!(decision.reasons, vec![VisibilityReason::Installer]);
    }

    #[test]
    fn product_matched_cli_in_user_bin_remains_primary() {
        let mut app = candidate(
            "Claude Code",
            r"C:\Users\Maks\.local\bin\claude.exe",
            SourceKind::Portable,
        );
        app.product_name = Some("Claude Code".into());
        app.publisher = Some("Anthropic PBC".into());
        app.description = Some("Claude Code".into());

        let decision = classify_visibility(&app);

        assert_eq!(decision.class, VisibilityClass::Primary);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::ExecutableProductMatch));
    }

    #[test]
    fn bundled_toolchain_binary_remains_auxiliary_despite_product_metadata() {
        let mut app = candidate(
            "The OpenSSL Toolkit",
            r"D:\Git\mingw64\bin\openssl.exe",
            SourceKind::Portable,
        );
        app.product_name = Some("The OpenSSL Toolkit".into());
        app.publisher = Some("The OpenSSL Project".into());
        app.description = Some("OpenSSL application".into());

        assert_eq!(classify_visibility(&app).class, VisibilityClass::Auxiliary);
    }

    // "VLC media player - reset preferences and cache files" runs vlc.exe in a wipe mode; it must
    // not be shown as the player.
    #[test]
    fn vlc_reset_maintenance_shortcut_is_rejected() {
        let mut app = candidate(
            "VLC media player - reset preferences and cache files",
            r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\VideoLAN\VLC media player - reset preferences and cache files.lnk",
            SourceKind::StartMenu,
        );
        app.resolved_path = Some(r"C:\Program Files\VideoLAN\VLC\vlc.exe".into());

        assert_eq!(classify_visibility(&app).class, VisibilityClass::Rejected);
    }

    // A VS developer prompt reaches the catalog as an AUMID Start-App, which normally forces
    // Primary. As a command environment it must still be Auxiliary.
    #[test]
    fn visual_studio_command_prompt_is_auxiliary_despite_aumid() {
        let mut native = candidate(
            "x64 Native Tools Command Prompt for VS 2019",
            "Microsoft.AutoGenerated.{FF70D809-A022-5972-850F-19E0AA8C07C2}",
            SourceKind::StartApps,
        );
        native.launch_kind = LaunchKind::AppUserModelId;

        let decision = classify_visibility(&native);
        assert_eq!(decision.class, VisibilityClass::Auxiliary);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::CommandEnvironment));
    }

    // Command Prompt and a `cmd.exe /k <bat>` wrapper are command environments. Argument-free
    // Windows PowerShell remains a normal launcher entry.
    #[test]
    fn command_prompts_are_auxiliary_but_plain_powershell_stays_primary() {
        let mut node = candidate(
            "Node.js command prompt",
            r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js\Node.js command prompt.lnk",
            SourceKind::StartMenu,
        );
        node.resolved_path = Some(r"C:\Windows\System32\cmd.exe".into());
        node.launch_arguments = Some(r#"/k "C:\Program Files\nodejs\nodevars.bat""#.into());
        assert_eq!(classify_visibility(&node).class, VisibilityClass::Auxiliary);

        let mut command_prompt = candidate(
            "Command Prompt",
            r"C:\Menu\Command Prompt.lnk",
            SourceKind::StartMenu,
        );
        command_prompt.resolved_path = Some(r"C:\Windows\System32\cmd.exe".into());
        assert_eq!(
            classify_visibility(&command_prompt).class,
            VisibilityClass::Auxiliary
        );

        let mut shell = candidate(
            "Windows PowerShell",
            r"C:\Menu\Windows PowerShell\Windows PowerShell.lnk",
            SourceKind::StartMenu,
        );
        shell.resolved_path =
            Some(r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe".into());
        assert_eq!(classify_visibility(&shell).class, VisibilityClass::Primary);
    }

    // The command-environment rule requires an interpreter host: a normal application launched
    // with arguments (but resolving to its own exe) must not be demoted to auxiliary.
    #[test]
    fn app_with_arguments_but_non_host_target_stays_primary() {
        let mut app = candidate("Some App", r"C:\Menu\Some App.lnk", SourceKind::StartMenu);
        app.resolved_path = Some(r"C:\Program Files\SomeApp\app.exe".into());
        app.launch_arguments = Some("--flag value".into());
        assert_eq!(classify_visibility(&app).class, VisibilityClass::Primary);
    }

    // Real corpus: interpreter-hosted dev tools and a diagnostic launcher are auxiliary, not
    // applications a launcher user picks to open.
    #[test]
    fn python_idle_mysql_client_and_safe_mode_are_auxiliary() {
        let mut idle = candidate(
            "IDLE (Python 3.14 64-bit)",
            r"C:\Menu\Python 3.14\IDLE (Python 3.14 64-bit).lnk",
            SourceKind::StartMenu,
        );
        idle.resolved_path = Some(r"C:\Python314\pythonw.exe".into());
        idle.launch_arguments = Some(r#""C:\Python314\Lib\idlelib\idle.pyw""#.into());
        assert_eq!(classify_visibility(&idle).class, VisibilityClass::Auxiliary);

        let mut mysql = candidate(
            "MySQL 8.0 Command Line Client",
            r"C:\Menu\MySQL\MySQL 8.0 Command Line Client.lnk",
            SourceKind::StartMenu,
        );
        mysql.resolved_path = Some(r"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe".into());
        mysql.launch_arguments = Some(r#""-uroot" "-p""#.into());
        assert_eq!(
            classify_visibility(&mysql).class,
            VisibilityClass::Auxiliary
        );

        // Name-based: soffice.exe is the app itself, so only the "safe mode" name marks it.
        let mut safe = candidate(
            "LibreOffice (Безопасный режим)",
            r"C:\Menu\LibreOffice\LibreOffice (Безопасный режим).lnk",
            SourceKind::StartMenu,
        );
        safe.resolved_path = Some(r"C:\Program Files\LibreOffice\program\soffice.exe".into());
        safe.launch_arguments = Some("--safe-mode".into());
        assert_eq!(classify_visibility(&safe).class, VisibilityClass::Auxiliary);
    }

    // A `rundll32.exe`-hosted config shortcut (Configure x264vfw) and a setup Start-App (Install
    // Additional Tools for Node.js) are not applications.
    #[test]
    fn rundll32_config_and_node_setup_are_auxiliary() {
        let mut x264 = candidate(
            "Configure x264vfw",
            r"C:\Menu\x264vfw\Configure x264vfw.lnk",
            SourceKind::StartMenu,
        );
        x264.resolved_path = Some(r"C:\Windows\SysWOW64\rundll32.exe".into());
        x264.launch_arguments = Some("x264vfw.dll,Configure".into());
        assert_eq!(classify_visibility(&x264).class, VisibilityClass::Auxiliary);

        let mut node = candidate(
            "Install Additional Tools for Node.js",
            "Microsoft.AutoGenerated.{04770C2D}",
            SourceKind::StartApps,
        );
        node.launch_kind = LaunchKind::AppUserModelId;
        assert_eq!(classify_visibility(&node).class, VisibilityClass::Auxiliary);
    }

    // A bundled `*Util.exe` (e.g. AstUtil.exe of "Ассистент") is a utility component, not the app.
    #[test]
    fn bundled_utility_executable_is_auxiliary() {
        let app = candidate(
            "Ассистент",
            r"D:\разный хлам\Ассистент\AstUtil.exe",
            SourceKind::Portable,
        );
        assert_eq!(classify_visibility(&app).class, VisibilityClass::Auxiliary);
    }

    #[test]
    fn oracle_java_runtime_entries_are_auxiliary() {
        for name in ["Java(TM) Platform SE", "Java(TM) SE Development Kit"] {
            let app = candidate(
                name,
                r"C:\Program Files\Java\jre\bin\javaw.exe",
                SourceKind::StartMenu,
            );
            assert_eq!(
                classify_visibility(&app).class,
                VisibilityClass::Auxiliary,
                "{name}"
            );
        }
    }

    #[test]
    fn synthetic_fixture_corpus_matches_manual_labels() {
        let fixtures: Vec<Fixture> = serde_json::from_str(include_str!(
            "../../../tests/fixtures/catalog_visibility.json"
        ))
        .unwrap();
        assert!(
            fixtures.len() < 100,
            "synthetic corpus must not be presented as real-world validation"
        );
        for fixture in fixtures {
            let mut app = candidate(&fixture.name, &fixture.path, fixture.source);
            app.description = fixture.description;
            app.publisher = fixture.publisher;
            app.original_filename = fixture.original_filename;
            app.resolved_path = fixture.resolved_path;
            app.can_uninstall = fixture.can_uninstall.unwrap_or(false);
            let actual = classify_visibility(&app);
            let matches = match fixture.expected.as_str() {
                "primary" => actual.class == VisibilityClass::Primary,
                "auxiliary" | "uncertain" => actual.class == VisibilityClass::Auxiliary,
                "rejected" => actual.class == VisibilityClass::Rejected,
                label => panic!("unknown fixture label: {label}"),
            };
            assert!(
                matches,
                "{}: expected {}, got {:?} ({:?})",
                fixture.name, fixture.expected, actual.class, actual.reasons
            );
        }
    }

    #[test]
    fn msix_framework_packages_are_rejected() {
        for name in [
            "Microsoft.VCLibs.140.00",
            "Microsoft.UI.Xaml.2.8",
            "Microsoft.NET.Native.Framework.2.2",
            "Microsoft.Web.WebView2",
        ] {
            let app = candidate(name, name, SourceKind::Msix);
            let decision = classify_visibility(&app);
            assert_eq!(decision.class, VisibilityClass::Rejected, "{name}");
            assert!(decision
                .reasons
                .contains(&VisibilityReason::FrameworkPackage));
        }
        // A real Store app whose name merely mentions a runtime is unaffected.
        let real = candidate(
            "WebView2 Sample App",
            "Contoso.WebView2Sample_8wekyb!App",
            SourceKind::Msix,
        );
        assert_ne!(classify_visibility(&real).class, VisibilityClass::Rejected);
    }

    #[test]
    fn dead_autogenerated_start_app_is_auxiliary() {
        // A "Windows Software Development Kit" folder synthesized into an AutoGenerated AUMID with
        // no launch target cannot open anything.
        let mut sdk = candidate(
            "Windows Software Development Kit",
            "Microsoft.AutoGenerated.{3B6E7DF3-19A3-70DB}",
            SourceKind::StartApps,
        );
        sdk.launch_kind = LaunchKind::AppUserModelId;
        assert_eq!(classify_visibility(&sdk).class, VisibilityClass::Auxiliary);

        // A real Store app keeps its package-family AUMID and stays Primary.
        let mut calc = candidate(
            "Calculator",
            "Microsoft.WindowsCalculator_8wekyb3d8bbwe",
            SourceKind::StartApps,
        );
        calc.launch_kind = LaunchKind::AppUserModelId;
        assert_eq!(classify_visibility(&calc).class, VisibilityClass::Primary);
    }

    #[test]
    fn bundled_codeium_chromium_is_auxiliary() {
        for (name, path) in [
            (
                "chrome",
                r"C:\Users\Maks\.codeium\ws-browser\chromium-1155\chrome-win\chrome.exe",
            ),
            (
                "chrome pwa launcher",
                r"C:\Users\Maks\.codeium\ws-browser\chromium-1155\chrome-win\chrome_pwa_launcher.exe",
            ),
        ] {
            let app = candidate(name, path, SourceKind::Portable);
            assert_eq!(
                classify_visibility(&app).class,
                VisibilityClass::Auxiliary,
                "{name}"
            );
        }
    }

    #[test]
    fn architecture_stub_executable_is_auxiliary() {
        // A bare "32.exe" carrying another vendor's metadata (a Yandex binary dropped in a
        // "Крипто про" folder) is a component/stub, not the app the folder name implies.
        let mut stub = candidate(
            "Крипто 4",
            r"E:\Apps\Крипто про\Крипто 4\32.exe",
            SourceKind::Portable,
        );
        stub.publisher = Some("YANDEX LLC".into());
        stub.product_name = Some("Yandex".into());
        stub.description = Some("Yandex".into());
        let decision = classify_visibility(&stub);
        assert_eq!(decision.class, VisibilityClass::Auxiliary);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::ProductComponent));

        // A normal executable whose name merely ends in "32" stays a candidate app.
        let win = candidate(
            "WinThing",
            r"D:\Apps\WinThing\win32.exe",
            SourceKind::Portable,
        );
        assert!(!classify_visibility(&win)
            .reasons
            .contains(&VisibilityReason::ProductComponent));
    }

    #[test]
    fn explorer_folder_shortcut_is_rejected_but_file_explorer_stays() {
        // "Windows Software Development Kit" is a .lnk that opens the Windows Kits folder in Explorer.
        let mut sdk = candidate(
            "Windows Software Development Kit",
            r"C:\Menu\Windows Kits\Windows Software Development Kit.lnk",
            SourceKind::StartMenu,
        );
        sdk.resolved_path = Some(r"C:\Windows\explorer.exe".into());
        sdk.launch_arguments = Some(r#""C:\Program Files (x86)\Windows Kits\10\""#.into());
        let decision = classify_visibility(&sdk);
        assert_eq!(decision.class, VisibilityClass::Rejected);
        assert!(decision
            .reasons
            .contains(&VisibilityReason::ShellLocationShortcut));

        // The real File Explorer targets a bare explorer.exe with no argument and stays a normal app.
        let mut explorer = candidate("Проводник", r"C:\Menu\Проводник.lnk", SourceKind::StartMenu);
        explorer.resolved_path = Some(r"C:\Windows\explorer.exe".into());
        assert_ne!(
            classify_visibility(&explorer).class,
            VisibilityClass::Rejected
        );
    }

    #[test]
    fn bundled_self_extractor_installer_is_rejected() {
        // Adobe Reader installer stub bundled inside another product's \support\ folder.
        let mut adobe = candidate(
            "Adobe Self Extractor",
            r"E:\Apps\KOMPAS-3D V19\support\Adobe\AdbeRdr11000_ru_RU.exe",
            SourceKind::Portable,
        );
        adobe.publisher = Some("Adobe Systems Incorporated".into());
        adobe.product_name = Some("Adobe Self Extractor".into());
        let decision = classify_visibility(&adobe);
        assert_eq!(decision.class, VisibilityClass::Rejected);
        assert_eq!(decision.reasons, vec![VisibilityReason::Installer]);
    }

    #[test]
    fn expanded_maintenance_markers_are_rejected() {
        for (name, path) in [
            ("Elevation Service", r"C:\App\elevation service.exe"),
            ("Crash Reporter", r"C:\App\werfault.exe"),
            ("Telemetry", r"C:\App\telemetry-service.exe"),
            ("Update", r"C:\App\squirrel.exe"),
        ] {
            let app = candidate(name, path, SourceKind::Portable);
            assert_eq!(
                classify_visibility(&app).class,
                VisibilityClass::Rejected,
                "{name}"
            );
        }
    }

    #[test]
    fn sdk_sample_executables_are_auxiliary() {
        // A shared-memory sample bundled in a product's SDK tree is reference code, not an app.
        let mut sample = candidate(
            "RTSSSharedMemorySample Application",
            r"D:\Apps\RivaTuner Statistics Server\SDK\Samples\SharedMemory\RTSSSharedMemorySample\Release\RTSSSharedMemorySample.exe",
            SourceKind::Portable,
        );
        sample.description = Some("RTSS shared memory sample".into());
        let decision = classify_visibility(&sample);
        assert_eq!(decision.class, VisibilityClass::Auxiliary);
        assert!(decision.reasons.contains(&VisibilityReason::SdkSample));

        // A normal app that merely has "sample" in its name (not "sample application") and no SDK
        // path is unaffected.
        let mut normal = candidate(
            "Sample Notes",
            r"D:\Apps\SampleNotes\SampleNotes.exe",
            SourceKind::Portable,
        );
        normal.publisher = Some("Acme".into());
        normal.description = Some("Sample Notes desktop app".into());
        assert!(!classify_visibility(&normal)
            .reasons
            .contains(&VisibilityReason::SdkSample));
    }

    #[test]
    fn portable_without_any_metadata_in_runtime_path_is_auxiliary() {
        // No version, publisher, or product name, and it sits under a runtime \bin\ directory.
        let bare = candidate("tool", r"D:\App\bin\tool.exe", SourceKind::Portable);
        assert_eq!(classify_visibility(&bare).class, VisibilityClass::Auxiliary);

        // A portable app that does carry coherent product metadata stays Primary.
        let mut real = candidate(
            "AcmeTool",
            r"D:\Apps\AcmeTool\AcmeTool.exe",
            SourceKind::Portable,
        );
        real.publisher = Some("Acme Software".into());
        real.description = Some("Acme Tool desktop application".into());
        real.product_name = Some("AcmeTool".into());
        assert_eq!(classify_visibility(&real).class, VisibilityClass::Primary);
    }

    #[test]
    fn applies_explainable_decision_to_catalog_entry() {
        let mut app = candidate("iconv", r"C:\Git\usr\bin\iconv.exe", SourceKind::Portable);

        apply_visibility(&mut app);

        assert_eq!(app.visibility_class, VisibilityClass::Auxiliary);
        assert!(app.visibility_score < 0);
        assert!(app
            .visibility_reasons
            .contains(&VisibilityReason::ProductComponent));
    }
}
