//! Field-scoped signal extraction shared by the artifact and visibility classifiers.
//!
//! Every marker used to match a plain substring of one blob holding the name, the path, the
//! resolved target, the original filename, the product name and the description at once. A word
//! anywhere decided the record's fate, which does not generalize past the machine the needle list
//! was written on: `squirrel` in an AppUserModelId removed every Squirrel-packaged application,
//! `compiler` in a PE description demoted a developer tool, `manual` in a folder name hid an app.
//!
//! This mirrors `classify::signals`, which already separates its fields for the same reason. A
//! needle now has to say *where* it is evidence, so a word in prose cannot masquerade as a file
//! name and an opaque identifier cannot masquerade as either.
//!
//! The field a needle is bound to also decides how much authority it may have. `FileName` and the
//! PE-authored parts of `Prose` are written by the vendor and read the same on every machine;
//! `Name` is localized, user-editable and vendor-inconsistent, so a `Name` needle may demote or
//! reclassify a record into a visible list but must never remove it. See
//! `docs/superpowers/specs/2026-08-02-classification-generalization-design.md`.

use crate::catalog::{AppInfo, LaunchKind};
use std::path::Path;

/// Where a marker looks. See `MarkerFields::matches` for the exact semantics of each.
#[derive(Clone, Copy)]
pub(in crate::catalog) enum Field {
    /// Substring of the display name alone.
    Name,
    /// Substring of any file name this record points at — its own path, its resolved target, and
    /// the `OriginalFilename` recorded in the executable's version resource.
    FileName,
    /// Substring of the filesystem paths. Never an AppUserModelId.
    Path,
    /// Substring of the human-readable fields: display name, PE description, PE product name.
    Prose,
}

pub(in crate::catalog) struct MarkerFields {
    name: String,
    file_names: String,
    paths: String,
    prose: String,
}

impl MarkerFields {
    pub(in crate::catalog) fn from_app(app: &AppInfo) -> Self {
        // An AppUserModelId is an opaque identifier, not a path and not prose:
        // `com.squirrel.Foo.Foo`, `Microsoft.AutoGenerated.{GUID}`, `Publisher.App_hash!App`.
        // It never reaches a text field. Structural rules that genuinely need it read `app.path`
        // directly.
        let launch_path = (app.launch_kind != LaunchKind::AppUserModelId).then_some(&app.path);
        let resolved = app.resolved_path.as_deref().unwrap_or_default();
        let original = app.original_filename.as_deref().unwrap_or_default();
        let name = app.name.to_lowercase();
        let description = app
            .description
            .as_deref()
            .unwrap_or_default()
            .to_lowercase();
        let product = app
            .product_name
            .as_deref()
            .unwrap_or_default()
            .to_lowercase();

        let file_names = [
            launch_path.map(String::as_str).unwrap_or_default(),
            resolved,
            original,
        ]
        .iter()
        .map(|value| file_name_of(value))
        .collect::<Vec<_>>()
        .join(" ");

        let paths = [
            launch_path.map(String::as_str).unwrap_or_default(),
            resolved,
            app.install_location.as_deref().unwrap_or_default(),
        ]
        .join(" ")
        .to_lowercase()
        .replace('/', r"\");

        Self {
            prose: format!("{name} {description} {product}"),
            name,
            file_names,
            paths,
        }
    }

    pub(in crate::catalog) fn matches(&self, field: Field, needle: &str) -> bool {
        match field {
            Field::Name => self.name.contains(needle),
            Field::FileName => self.file_names.contains(needle),
            Field::Path => self.paths.contains(needle),
            Field::Prose => self.prose.contains(needle),
        }
    }

    pub(in crate::catalog) fn any(&self, field: Field, needles: &[&str]) -> bool {
        needles.iter().any(|needle| self.matches(field, needle))
    }
}

/// Lowercased file name with its extension (`update.exe`), or the whole value when it has no path
/// separator to strip — a bare `OriginalFilename` is already a file name.
fn file_name_of(value: &str) -> String {
    let trimmed = value.trim().trim_matches('"');
    Path::new(trimmed)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(trimmed)
        .to_lowercase()
}
